### PR TITLE
[Augur_PHB] Update ncov repo commit and remove reference input to augur clades task

### LINKED ISSUE #234: Augur_PHB: cannot color auspice tree by clade
:bug:

### :pencil: Describe the Issue

The output auspice input JSON file incorrectly lists "unassigned" in the "clade_membership" field for all samples, meaning that Auspice is unable to color the tree by the clade membership.

Short term solution - drag and drop the final output metadata TSV into Auspice so that the tips are colored with clade

Long term solution - investigate why the Augur workflow is not assigning clades properly. 

### :repeat: How to Reproduce

- Was this run on the Terra platform?
  - Terra on GCP or Azure?
- Or were the workflows run locally using `miniwdl` or `cromwell`?
  - **What was the exact command was used to launch the workflow?**
- If possible, we may ask you to share your Terra workspace with us. Usually READER access is sufficient, but we may ask for WRITER access if we need to make changes to the workspace to reproduce the issue.

### PR DESCRIPTION
**Pull request by sage-wright**
This PR closes #234!

🗑️ This dev branch should be deleted after merging to main.

## :hammer_and_wrench:  Impacted Workflows/Tasks & Changes Being Made
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : Yes

- The ncov repo commit change will cause all future *SARS-CoV-2* Augur trees to be built with updated lineages and clades as of 2024-02-01.

Running this workflow on different occasions could result in different results, e.g. due to use of a live database, "latest" docker image, or stochastic data processing : No 

#### 🔄 Data Processing 

Docker/software or software versions changed: 

Databases or database versions changed:

in the `set_sc2_defaults` task, the `nextstrain_ncov_repo_commit` was updated from "23d1243127e8838a61b7e5c1a72bc419bf8c5a0d" to "cec4fa0ecd8612e4363d40662060a5a9c712d67e" which differ in about 11 months of age. 

Data processing/commands changed:

In `task_augur_clades.wdl`, the `augur_clades` task had previously used the `--references "{reference_fasta}"` input, but this was not implemented in the `augur clades` command, leading to a warning. 

File processing changed:

Compute resources changed:

#### ➡️ Inputs 

The optional input `nextstrain_ncov_repo_commit` was updated to "cec4fa0ecd8612e4363d40662060a5a9c712d67e" and will affect all users if the input is left blank.

#### ⬅️ Outputs 

The `clades_tsv` file will now contain clades (intermediate file, not sent to Terra table), and the `auspice_input_json` file will now be able to be colored by clade.

#### Test Dataset

We tested on 7 SARS-CoV-2 Omicron samples from different Omicron clades.

#### Command-line Testing with MiniWDL or Cromwell (optional)

Command-line testing did not occur.

#### Terra Testing

[This job](https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-theiagen-validations/job_history/8f7d0f43-be9b-4d71-b575-8e130bcb2bb6) demonstrates the correct output behavior from `augur clades`.

#### Suggested Scenarios for Reviewer to Test

More SC2 samples. Additionally, flu and mpox should be tested as well.

#### Theiagen Version Release Testing (optional)

In the release, this PR will require:
- validation testing (visual check)
- no new samples
- The `auspice_input_json` should be checked and compared with previous versions.

## :microscope: Final Developer Checklist

- [x] The workflow/task has been tested locally and results, including file contents, are as anticipated
- [x] The workflow/task has been tested on Terra and results, including file contents, are as anticipated
- [x] The CI/CD has been adjusted and tests are passing (to be completed by Theiagen developer)
- [x] Code changes follow the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-bb456f34322d4f4db699d4029050481c)

## 🎯 Reviewer Checklist 

- [x] All impacted workflows/tasks have been tested on Terra with a different dataset than used for development
- [x] All reviewer-suggested scenarios have been tested and any additional
- [ ] All changed results have been confirmed to be accurate
- [ ] All workflows/tasks impacted by change/s have been tested using a standard validation dataset to ensure no unintended change of functionality
- [x] All code adheres to the style guide
- [ ] MD5 sums have been updated
- [x] The PR author has addressed all comments

## 🗂️ Associated Documentation (to be completed by Theiagen developer)

- [ ] Relevant documentation on the Public Health Resources "PHB Main" has been updated
- [x] Workflow diagrams have been updated to reflect changes

### CODE REVIEW

**Comment by kapsakcj** [comment]
Reminder to myself: notify one laboratory (PR) that might be using this when PR is merged & dev branch is deleted

**Comment by jrotieno** [comment]
@sage-wright getting an error: 
```
Error updating config
Failed to process workflow definition 'augur' (reason 1 of 1): Failed to process 'call clades_task.augur_clades' (reason 1 of 1): The call supplied a value 'reference_fasta' that doesn't exist in the task (or sub-workflow)
```

This has to do with the `reference_fasta` input commented out in the clades_task. Should that be reverted back?

**Comment by sage-wright** [comment]
No, it shouldn't be reverted since it was not used. We should remove the reference in the workflow.

**Comment by sage-wright** [comment]
@jrotieno, I fixed it!

**Review by jrotieno — APPROVED** [review]
After the fix, works as expected. Tested on Flu.

**Pull request merged**
