### PR TITLE
[Internal] Updating runtime parameters

### LINKED ISSUE #483: Change version_capture container
:bug:

### :pencil: Describe the Issue
task_versioning.wdl is called every time a workflow is run. 
The docker container it calls is Ubuntu which is massive.  All it does is write some a version number and date. Change this to a very small docker container like alpine. This will reduce the cost of every workflow run by a little bit.

https://hub.docker.com/_/alpine

Upload the container used to our Google Artifact Registry.

This task runs for an average of 1 second. Make it preemptible (spot) so that we can access lower pricing. Google give 30 seconds notice before killing it, so we shouldn't notice any difference.

In the runtime section of the task set:

maxRetries: 3
preemptible: 1

### LINKED ISSUE #485: shovill-pe CPUs not set in task
:bug:

### :pencil: Describe the Issue
The shovill-pe task doesnt take CPUs as input so defaults to 8, however only 4 are passed in.  

Pass in the correct number of CPUs in the task.
Run the task and figure out how much RAM is normally used (/usr/bin/time -v cmd). 
Does it really need 16GB? 
Does it require a 100GB local disk?
How much processing time is used and calculate the utilisation of the CPUs? If its not making use of all 4, adjust the task to use less.

### LINKED ISSUE #487: ksnp3 doesn't have CPUs passed in
:bug:

### :pencil: Describe the Issue
The ksnp3 task doesnt take CPUs as input. Check what happens. Does it use all available CPUs?  
This is the most expensive task to run currently ($30.80 per 1000 runs).

Run the task and figure out how much RAM is normally used (/usr/bin/time -v cmd). 
Does it really need 8GB? 
Does it require a 100GB local disk?
How much processing time is used and calculate the utilisation of the CPUs? If its not making use of all 4, adjust the task to use less.

### LINKED ISSUE #488: Check RAM Midas uses
:bug:

### :pencil: Describe the Issue
The midas task requests a huge amount of RAM (32GB).  This is an expensive VM configuration, particularly now that its run automatically from TheiaProk.

Run the task and figure out how much RAM is normally used (/usr/bin/time -v cmd). 
Does it really need 32GB? 
Does it require a 100GB local disk?
How much processing time is used and calculate the utilisation of the CPUs? If its not making use of all 4, adjust the task to use less. I it is using all 4, consider bumping it to 8 to reduce the amount of time we are using 32GB RAM. 
Is this task IO bound? 

This task is short. Make it preemptible (spot) so that we can access lower pricing. Google give 30 seconds notice before killing it, so we shouldn't notice any difference.

In the runtime section of the task set:

    maxRetries: 3
    preemptible: 1

### LINKED ISSUE #489: Reduce Gambit task resource requirements
:bug:

### :pencil: Describe the Issue
Gambit is very efficient with its resource usage. 

Modify the task resources to 1 CPU, 2 GB RAM and 20 GB local disk.
Modify the task to pass in the number of CPUs.
Test this works.

This task runs for an average of 6 seconds. Make it preemptible (spot) so that we can access lower pricing. Google give 30 seconds notice before killing it, so we shouldn't notice any difference.

In the runtime section of the task set:

    maxRetries: 3
    preemptible: 1

### LINKED ISSUE #490: Check cg-pipeline CPUs used
:bug:

### :pencil: Describe the Issue
The cg-pipeline task doesnt take CPUs as input. 4 are passed in. Does it use all available?

Pass in the set number of CPUs in the task.
Run the task and figure out how much RAM is normally used (/usr/bin/time -v cmd). 
Does it really need 8GB? 
Does it require a 100GB local disk?
How much processing time is used and calculate the utilisation of the CPUs? If its not making use of all 4, adjust the task to use less.

This task is very short. Make it preemptible (spot) so that we can access lower pricing. Google give 30 seconds notice before killing it, so we shouldn't notice any difference.

In the runtime section of the task set:

    maxRetries: 3
    preemptible: 1

### LINKED ISSUE #491: Update check-reads to use less CPUs
:bug:

### :pencil: Describe the Issue
The check-reads task only uses 1 CPU but 2 are requested for the VM.

Change the CPUs to 1. 

This task is very short. Make it preemptible (spot) so that we can access lower pricing. Google give 30 seconds notice before killing it, so we shouldn't notice any difference.

In the runtime section of the task set:

    maxRetries: 3
    preemptible: 1

### LINKED ISSUE #492: Make busco preemptible
:bug:

### :pencil: Describe the Issue

This task is very short. Make it preemptible (spot) so that we can access lower pricing. Google give 30 seconds notice before killing it, so we shouldn't notice any difference.

In the runtime section of the task set:

    maxRetries: 3
    preemptible: 1

### LINKED ISSUE #493: Make MIDAS optional in TheiaProk
:bug:

### :pencil: Describe the Issue

Make MIDAS optional in TheiaProk. It costs a fair bit to run so only run it if specifically requested.

### PR DESCRIPTION
**Pull request by sage-wright**
This one is a doozy. 

This PR:
- closes #483
- closes #485 
- closes #487 
- closes #488 
- closes #489 
- closes #490 
- closes #491 
- closes #492 
- closes #493 

🗑️ This dev branch should be deleted after merging to main.

## :brain: Aim, Context and Functionality
Many tasks require far more runtime parameters than are actually used. This PR adjusts various runtime parameters accordingly.

## :hammer_and_wrench:  Impacted Workflows/Tasks & Changes Being Made
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : No

Running this workflow on different occasions could result in different results, e.g. due to use of a live database, "latest" docker image, or stochastic data processing : No 

- No change in workflow function, just optimization of resources

#### 🔄 Data Processing 

Compute resources changed:
- many, see also code changes

#### ➡️ Inputs 

None 

#### ⬅️ Outputs 

None

#### Suggested Scenarios for Reviewer to Test

Ensure costs and runtime attributes went down as expected.

#### Theiagen Version Release Testing (optional)

None

## :microscope: Final Developer Checklist

- [x] The workflow/task has been tested locally and results, including file contents, are as anticipated
- [ ] The workflow/task has been tested on Terra and results, including file contents, are as anticipated
- [x] The CI/CD has been adjusted and tests are passing (to be completed by Theiagen developer)
- [x] Code changes follow the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-bb456f34322d4f4db699d4029050481c)

## 🎯 Reviewer Checklist 

- [x] All impacted workflows/tasks have been tested on Terra with a different dataset than used for development
- [x] All reviewer-suggested scenarios have been tested and any additional
- [x] All changed results have been confirmed to be accurate
- [x] All workflows/tasks impacted by change/s have been tested using a standard validation dataset to ensure no unintended change of functionality
- [x] All code adheres to the style guide
- [x] MD5 sums have been updated
- [x] The PR author has addressed all comments

## 🗂️ Associated Documentation (to be completed by Theiagen developer)

- [ ] Relevant documentation on the Public Health Resources "PHB Main" has been updated
- [ ] Workflow diagrams have been updated to reflect changes

### CODE REVIEW

**Comment by AndrewLangvt** [comment]
TheiaProk_Illumina_PE_PHB - https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Lang_Sandbox/job_history/4fa24d88-2417-4fa3-a3e1-3f4268ca1198
shovil - confirmed CPUs are passed to shovil command 
busco - confirmed preemtible
gambit - confirmed disk size 20, confirmed mem 2, CPU 1

realized I had to pass in flag to run midas- https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Lang_Sandbox/job_history/1fa8a187-17f8-4638-9ba3-965adb8e1c73
midas - confirmed preemtible, mem = 4

@jrotieno from my perspective, once you review your set of these workflows, you can mark it approved for merge

**Comment by jrotieno** [comment]
@AndrewLangvt maybe you just need to mark the ones you went through as done on the board?

**Comment by AndrewLangvt** [comment]
@jrotieno good call; done!

**Review by jrotieno — APPROVED** [review]
@AndrewLangvt and I have reviewed the changes and approve. Well done @sage-wright

**Pull request merged**
