### PR TITLE
[TheiaCoV] Reorder flu segments from largest to smallest in irma task

### LINKED ISSUE #630: [TheiaCoV] Reorder flu assembly segments in largest-to-smallest order
:cool:

### :pushpin: Explain the Request

Re-ordering of the flu segments in the assembly_fasta file output by TheiaCoV in largest to smallest order: PB1, PB2, PA, HA, NP, NA, MP, NS, in accordance with Nextstrain/UShER formatting.

### PR DESCRIPTION
**Pull request by Michal-Babins**
This PR closes #630 

🗑️ This dev branch should <NOT> be deleted after merging to main.

## :brain: Summary

PR updates TheiaCoV workflow for when "flu" organism is chosen, and reorders flue segments from largest to smallest in the irma task. 
## :zap: Impacted Workflows/Tasks

wf: TheiaCov
task: task_irma

This PR may lead to different results in pre-existing outputs: **Yes**

This PR uses an element that could cause duplicate runs to have different results: **Yes/No**

## :hammer_and_wrench: Changes

Changes take expected flu segment lengths (large to small) and concatenates them in the irma task to the irma consensus fasta in descending order

### :gear: Algorithm

In task_irma.wdl for the flu track of TheiaCoV, the process for creating the consensus fasta was updated to order the flu segments from largest to smallest `segments=("PB2" "PB1" "PA" "HA" "NP" "NA" "MP" "NS")` as per request, updating the assembly_fasta output. 

### ⬅️ Outputs

- assembly_fasta (when flu track is triggered)
## :test_tube: Testing

This PR was tested against flu data found in the flu_testing table [here](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Babinski_Sandbox/data). The workspace for testing this data can be found [here](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Babinski_Sandbox/job_history/42b14b65-0b37-4e4c-8127-154d256140a4).

Further testing was done on the theiacov validation set against [WNV](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Babinski_Sandbox/job_history/52959af0-4c09-4631-b6d9-4a90890ee2d5) and [MPXV](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Babinski_Sandbox/job_history/d9d5241b-addf-4de2-a89c-c64988ab57f1)

### Suggested Scenarios for Reviewer to Test

Test with flu set from flu_testing table [here](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Babinski_Sandbox/data). For flu ensure output fasta are in the following order of segments: `segments=("PB2" "PB1" "PA" "HA" "NP" "NA" "MP" "NS")`. Test with validation sets of your choosing. 

## :microscope: Final Developer Checklist

- [x] The workflow/task has been tested and results, including file contents, are as anticipated
- [x] The CI/CD has been adjusted and tests are passing (Theiagen developers)
- [x] Code changes follow the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-51b66a47dde54c798f35d673fff80249)
- [x] Documentation and/or workflow diagrams have been updated if applicable (Theiagen developers only)

## 🎯 Reviewer Checklist

- [x] All changed results have been confirmed
- [x] You have tested the PR appropriately (see the [testing guide](https://theiagen.notion.site/PR-Testing-Guide-Determining-Appropriate-Levels-of-Testing-4764e98a6aeb460185039c0896714590) for more information)
- [x] All code adheres to the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-51b66a47dde54c798f35d673fff80249)
- [x] MD5 sums have been updated
- [ ] The PR author has addressed all comments
- [ ] The documentation has been updated

### CODE REVIEW

**Comment by kapsakcj** [comment]
Tested here on a smattering of Flu A H1N1 and H3N2 samples as well as Flu B Victoria samples. Ignore the 1 unrelated failure due to corrupted FASTQs: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-Aug2024/job_history/a18bb52d-c992-4892-97c9-513257fc4280

Here's before and after of one sample's FASTA file containing all segments.

Before with v2.2.0:
image

After with this dev branch:
image

Downstream tasks like nextclade and VADR seem unimpacted ✅ , results match those from v2.2.0 analysis.

Could you please update the TheiaCoV docs, specifically in the section on IRMA, to mention that the default output file in the `assembly_fasta` column will be ordered from largest to smallest segment?

**Review by kapsakcj — CHANGES_REQUESTED** [review]
please update documentation in the TheiaCoV section on IRMA to mention the segment ordering in the output FASTA file

**Comment by Michal-Babins** [comment]
> please update documentation in the TheiaCoV section on IRMA to mention the segment ordering in the output FASTA file

Updated with latest commit.

**Review by kapsakcj — APPROVED** [review]
thanks for updating the docs!

**Pull request merged**
