### PR TITLE
PHBG v1.3.0 changes - vibrio subworkflow

### PR DESCRIPTION
**Pull request by cimendes**
This PR incorporates the latest changes made to PHBG in the v1.3.0 minor version release.

~~Setting as a draft until the release is made public.~~

### CODE REVIEW

**Comment by cimendes** [comment]
Successful run on Terra (failures were expected due to low quality test data): https://app.terra.bio/#workspaces/theiagen-validations/Theaigen-DEV-Vibrio-Subtyping/job_history/3e652e5a-c82f-47a8-a368-0b5f3e52e192

**Comment by cimendes** [comment]
@kevinlibuit This PR is ready for review :)

**Comment by cimendes** [comment]
image

This is a screenshot of the read file I've downloaded from Terra for that particular sample in that datatable. I noticed that the reads looked really odd (screenshot above). I've re-downloaded the reads one again using SRA_Fetch_PHB and reran the workflow just for this sample, and it succeeded without any issues: https://app.terra.bio/#workspaces/theiagen-validations/Theaigen-DEV-Vibrio-Subtyping/job_history/a343af78-8cd0-41df-ade4-d6ffb3f8c6b6

I'm blaming the read files on this one. I never seen this happen before. Here's the screenshot of the re-downloaded reads, looking much different from the original ones:
Image20230518095247

**Comment by kevinlibuit** [comment]
Yeah, that is really odd. Thanks for looking into that! Just wanted to make sure we didn't ignore a potential issue with trimmomatic. Otherwise changes look good. Appreciate you keeping things in sync with PHVG updates through the migration to PHB.

**Review by kevinlibuit — APPROVED** [review]

**Comment by michellescribner** [comment]
The merlin_magic workflow logic for the srst2_vibrio task was modified during PHB v1.0.0 validation to run only if not "ont_data" and not "assembly_only"

**Pull request merged**
