### PR TITLE
[ONT] Remove KMC

### LINKED ISSUE #203: Genome Size Estimation - Ways to improve
Currently we have `kmc` as our genome size estimator on TheiaProk suite of workflows. This has shown to be widely inconsistent on ONT data, particularly when very long read sequences are present in the input files 

There are several ways we can improve this step. Here's a few options:

1. **Hyperparameter tunning of `kmc` k-mer length depending on the sequencing instrument.** According to @frankambrosio3, lowering the k-mer length (e.g. 9) has been showing more accurate results for genome size estimation. An alternative is to lower this value for the TheiaProk_ONT task. An important note is that this parameter is not exposed on the workflow level, so it cannot be adjusted by the user. 
2. **Jellyfish has been shown to be useful to estimate genome sizes, particularly for long-read sequencing data.** A tutorial on how to accomplish this is available at https://bioinformatics.uconn.edu/genome-size-estimation-tutorial/ 
3. **Implement and validate the new https://github.com/theiagen/gambitsizer developed by @andrewjpage.** Uses k-mers to estimate number of genes, which is then used to extrapolate genome size (assumes gene length of 1000 bp).

### PR DESCRIPTION
**Pull request by sage-wright**
This PR closes #203 

🗑️ This dev branch should be deleted after merging to main.

## :brain: Summary

This PR removes the KMC module from the TheiaCoV and TheiaProk ONT workflows. In place of the estimated genome length in TheiaProk ONT, I have added a default genome length of 5 Mb, which is around .7 Mb larger than the average genome length as estimated by calculating the mean genome length of all bacteria included in [this](https://github.com/CDCgov/phoenix/blob/main/assets/databases/NCBI_Assembly_stats_20240124.txt) file. 

## :zap: Impacted Workflows/Tasks

TheiaProk_ONT and TheiaCoV_ONT

This PR may lead to different results in pre-existing outputs: **Yes**, assemblies generated may be different due to differences in the use of estimated genome length in RASUSA downsampling. 

This PR uses an element that could cause duplicate runs to have different results: **No**

### :gear: Algorithm

- 5 Mb is default genome size in the read_qc_trim_ont subworkflow.

### ➡️ Inputs

No

### ⬅️ Outputs

KMC outputs have been removed.

## :test_tube: Testing

Test on TheiaProk [here](https://app.terra.bio/#workspaces/theiagen-validations/sage/job_history/78103d11-7ced-4c6d-9991-0ddf757a911a)

Test on TheiaCoV (flu) [here](https://app.terra.bio/#workspaces/cdc-terra-resources/Theiagen_Wright_SC2_Sandbox/job_history/84228cb9-39d2-4c93-8756-4667d456eb09)

## :microscope: Final Developer Checklist

- [x] The workflow/task has been tested and results, including file contents, are as anticipated
- [x] The CI/CD has been adjusted and tests are passing (Theiagen developers)
- [x] Code changes follow the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-51b66a47dde54c798f35d673fff80249)
- [x] Documentation and/or workflow diagrams have been updated if applicable (Theiagen developers only)

## 🎯 Reviewer Checklist

- [x] All changed results have been confirmed
- [ ] You have tested the PR appropriately (see the [testing guide](https://theiagen.notion.site/PR-Testing-Guide-Determining-Appropriate-Levels-of-Testing-4764e98a6aeb460185039c0896714590) for more information)
- [x] All code adheres to the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-51b66a47dde54c798f35d673fff80249)
- [x] MD5 sums have been updated
- [ ] The PR author has addressed all comments
- [ ] The documentation has been updated

### CODE REVIEW

**Comment by cimendes** [comment]
TheiaProk_ONT_PHB Test:

- Tested with the following data. Expected genome size corresponds to the approximate size of the reference on NCBI (rounded to the nearest Mb) 
- Run: 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/iines/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/iines/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


entity:theiaprok_ont_nokmc_id | espected_length | expected_taxon | read1
-- | -- | -- | --
ERR8958704 | 5700000 | Klebsiella pneumoniae | gs://theiagen-large-public-files-rp/terra/phb-validation/theiaprok-ont-reads/ERR8958704_1.fastq.gz
ERR8958706 | 5700000 | Klebsiella pneumoniae | gs://theiagen-large-public-files-rp/terra/phb-validation/theiaprok-ont-reads/ERR8958706_1.fastq.gz
ERR8958710 | 5700000 | Klebsiella pneumoniae | gs://theiagen-large-public-files-rp/terra/phb-validation/theiaprok-ont-reads/ERR8958710_1.fastq.gz
ERR8958833 | 2900000 | Staphylococcus aureus | gs://theiagen-large-public-files-rp/terra/phb-validation/theiaprok-ont-reads/ERR8958833_1.fastq.gz
ERR8958851 | 2900000 | Staphylococcus aureus | gs://theiagen-large-public-files-rp/terra/phb-validation/theiaprok-ont-reads/ERR8958851_1.fastq.gz
ERR8958852 | 2900000 | Staphylococcus aureus | gs://theiagen-large-public-files-rp/terra/phb-validation/theiaprok-ont-reads/ERR8958852_1.fastq.gz
ERR8958857 | 6200000 | Pseudomonas aeruginosa | gs://theiagen-large-public-files-rp/terra/phb-validation/theiaprok-ont-reads/ERR8958857_1.fastq.gz
ERR8958858 | 6200000 | Pseudomonas aeruginosa | gs://theiagen-large-public-files-rp/terra/phb-validation/theiaprok-ont-reads/ERR8958858_1.fastq.gz
SAMN04961841 | 5000000 | Salmonella enterica | gs://theiagen-large-public-files-rp/terra/phb-validation/theiaprok-ont-reads/SRR19768527_1.fastq.gz
SAMN05250424 | 5000000 | Salmonella enterica | gs://theiagen-large-public-files-rp/terra/phb-validation/theiaprok-ont-reads/SRR19768533_1.fastq.gz
SAMN05596277 | 5000000 | Salmonella enterica | gs://theiagen-large-public-files-rp/terra/phb-validation/theiaprok-ont-reads/SRR19768539_1.fastq.gz
SAMN20849361 | 4800000 | Shigella sonnei | gs://theiagen-large-public-files-rp/terra/phb-validation/theiaprok-ont-reads/SRR18254047_1.fastq.gz
SAMN22657138 | 4800000 | Shigella sonnei | gs://theiagen-large-public-files-rp/terra/phb-validation/theiaprok-ont-reads/SRR18254048_1.fastq.gz
SAMN22962688 | 4800000 | Shigella sonnei | gs://theiagen-large-public-files-rp/terra/phb-validation/theiaprok-ont-reads/SRR18254049_1.fastq.gz



</body>

</html>

**Comment by cimendes** [comment]
The run succeeded and I've now managed to look at the results from the assembly lengths produced versus the expected genome size. The differences are very very small except for Shigella sonnei where the assemblies were around 10% larger than expected:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/iines/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/iines/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


entity:theiaprok_ont_nokmc_id | assembly_length | expected_length | Difference (%) | expected_taxon | gambit_predicted_taxon
-- | -- | -- | -- | -- | --
ERR8958704 | 5754162 | 5700000 | 1% | Klebsiella pneumoniae | Klebsiella pneumoniae
ERR8958706 | 5725948 | 5700000 | 0% | Klebsiella pneumoniae | Klebsiella pneumoniae
ERR8958710 | 5755096 | 5700000 | 1% | Klebsiella pneumoniae | Klebsiella pneumoniae
ERR8958833 | 2902609 | 2900000 | 0% | Staphylococcus aureus | Staphylococcus aureus
ERR8958851 | 2902596 | 2900000 | 0% | Staphylococcus aureus | Staphylococcus aureus
ERR8958852 | 2902610 | 2900000 | 0% | Staphylococcus aureus | Staphylococcus aureus
ERR8958857 | 6281842 | 6200000 | 1% | Pseudomonas aeruginosa | Pseudomonas aeruginosa
ERR8958858 | 6294596 | 6200000 | 2% | Pseudomonas aeruginosa | Pseudomonas aeruginosa
SAMN04961841 | 4833663 | 5000000 | 3% | Salmonella enterica | Salmonella enterica
SAMN05250424 | 4744535 | 5000000 | 5% | Salmonella enterica | Salmonella enterica
SAMN05596277 | 4786893 | 5000000 | 4% | Salmonella enterica | Salmonella enterica
SAMN20849361 | 5275674 | 4800000 | 10% | Shigella sonnei | Shigella sonnei
SAMN22657138 | 5356338 | 4800000 | 12% | Shigella sonnei | Shigella sonnei
SAMN22962688 | 5295788 | 4800000 | 10% | Shigella sonnei | Shigella sonnei



</body>

</html>


The reason why is beyond this PR . BUSCO duplication score is not awful. 
image

The results are concordant with what was obtained with PHB v2.1.0 (https://app.terra.bio/#workspaces/theiagen-validations/PHB_Validation_v2-1-0/data)
image

**Comment by cimendes** [comment]
@sage-wright Can you update the documentation while I test TheiaCoV?

**Comment by cimendes** [comment]
**TheiaCoV Illumina SE Test**:
- Tested on WNV, monkeypox and sc2
- Run: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/f634f5da-c435-43cd-9924-938f07eec236

**Comment by cimendes** [comment]
**TheiaCoV_ONT**:
- Flu, MPXV and SC2
- Run: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/d1c22ccb-4335-4fe4-8eb7-5e690c976349

**Comment by sage-wright** [comment]
@cimendes, documentation has been updated!

**Review by cimendes — APPROVED** [review]

**Pull request merged**
