### PR TITLE
SNP matrix reordering, data summary, and export_taxon_table rework

### LINKED ISSUE #11: import the rework export taxon table fix
will make life easier

### LINKED ISSUE #12: Need to update versioning
[Outputs PHBG version](https://github.com/theiagen/public_health_bioinformatics/blob/main/tasks/task_versioning.wdl#L11)

### LINKED ISSUE #13: add snp-dists rework here

### PR DESCRIPTION
**Pull request by sage-wright**
This PR closes #11 by adding the `export_taxon_tables` rework implemented in PHBG. This rework needs testing and further investigation because since we are using a Python dictionary, the attempt to export the `Array[File]? snippy_variants_outdir_tarball` variable isn't a simple copy-paste. Also, I think this variable isn't an Array anyways, so I just commented out all lines that reference it. It's not being used currently in TheiaEuk anyways so I figured that wasn't a big deal.

This PR also closes #13 by adding the SNP matrix reordering to the Snippy_Tree task. I have also added the `summarize_data` task that is going to be added to PHBG and appended that to the Snippy_Tree workflow. I also organized/consolidated the outputs for Snippy_Tree for easier look-back. These changes are to function exactly the same as the identical changes made to the phylogenetic workflows in PHBG.

Also figured I would close #12 (update versioning) so I made that change.

Successfully tested:
- [x] Snippy_Tree

### CODE REVIEW

**Comment by sage-wright** [comment]
Also figured I would close #12 so I made that change.

**Comment by sage-wright** [comment]
Requesting review from @frankambrosio3 regarding `export_taxon_table` and updating of version
Requesting review from @jrotieno and @emmadoughty regarding changes to Snippy_Tree

**Comment by sage-wright** [comment]
Changes requested by @emmadoughty in the PHBG repo have been applied here.

**Review by emmadoughty — CHANGES_REQUESTED** [review]
Great work getting this PR copied over to Snippy_Tree and other relevant PHBG workflows, Sage!

**Tests undertaken**

OR_PHL_Acinetobacter dataset with 

- Snippy_Tree: [https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Doughty_Sandbox/job_history/17ca8d14-0126-479d-880a-ab0ef6768d67](https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Doughty_Sandbox/job_history/17ca8d14-0126-479d-880a-ab0ef6768d67)

**Workflow completion**

- Snippy_Tree failed at summarize data task: [https://job-manager.dsde-prod.broadinstitute.org/jobs/97eb4dc4-802b-4e38-8c63-bd5c1c233cae](https://job-manager.dsde-prod.broadinstitute.org/jobs/97eb4dc4-802b-4e38-8c63-bd5c1c233cae)

**Code review**

I have *not* reviewed the code for this PR

Further review is needed after addressing comments re. Snippy_Tree

**Pull request merged**
