### PR TITLE
Add abricate as optional module

### LINKED ISSUE #398: [TheiaProk] Add abricate as optional module
:cool:

### PR DESCRIPTION
**Pull request by jrotieno**
This PR closes #398. 

🗑️ This dev branch should <NOT> be deleted after merging to main.

## :brain: Aim, Context and Functionality

Currently on the TheiaProk workflows and prior to this PR, only the `"AcinetobacterPlasmidTyping"` and `"vibrio"` abricate databases would be called when the gambit predicted pathogens are `"Acinetobacter baumannii"` and `"Vibrio" or "Vibrio cholerae"`, respectively.

This PR adds an optional abricate module for genomic characterization. With this module, a user could specify whether they want to run abricate as part of their **TheiaProk** analysis by setting the `call_abricate` optional input parameter to `true`, **default** is `false`,  with the additional option to specify the abricate database through the optional input parameter `abricate_db`, with the **default** database set to `"vfdb"`

## :hammer_and_wrench:  Impacted Workflows/Tasks & Changes Being Made
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : No

Running this workflow on different occasions could result in different results, e.g. due to use of a live database, "latest" docker image, or stochastic data processing : No 

#### 🔄 Data Processing 

Docker/software or software versions changed: No

Databases or database versions changed: No

Data processing/commands changed: Yes, new inputs and outputs

File processing changed:Yes, new inputs and outputs

Compute resources changed: No

#### ➡️ Inputs 

```
call_abricate
abricate_db
```

#### ⬅️ Outputs 

```
abricate_results_tsv
abricate_genes
abricate_database
abricate_version
abricate_docker
```

#### Terra Testing

**_C. diphtheria samples to check for toxin genes in vfdb in both PE and SE:_**
C. diphtheriae Illumina PE: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Scribner_Sandbox/job_history/1a071907-3f92-429d-aebd-eed796b32d80
C. diphtheriae Illumina SE: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Scribner_Sandbox/job_history/171a8575-fc99-4051-9bcd-df4885cbeaa2

**_V. cholerae:_** to compare the optional module with vfdb identified gene, srst2 genes and amrfinderplus_virulence_genes, such as ctxA
**_A. baummannii:_**  to compare the the optional module with vfdb identified genes and the default abricate_abaum genes
**_E. coli:_** to compare the the optional module with vfdb identified genes and amrfinderplus_virulence_genes
V. cholerae, A. baummannii and E.Coli Illumina PE: https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Otieno_Sandbox/job_history/f1a612b8-2966-4dec-8ac6-7f00ff263050
V. cholerae ONT: https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Otieno_Sandbox/job_history/29fc26b8-6605-43b9-8680-6d9ef1a6f784

#### Suggested Scenarios for Reviewer to Test

Additional pathogens with alternative abricate databases to vfdb

## :microscope: Final Developer Checklist

- [ ] The workflow/task has been tested locally and results, including file contents, are as anticipated
- [x] The workflow/task has been tested on Terra and results, including file contents, are as anticipated
- [x] The CI/CD has been adjusted and tests are passing (to be completed by Theiagen developer)
- [x] Code changes follow the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-bb456f34322d4f4db699d4029050481c)

## 🎯 Reviewer Checklist 

- [x] All impacted workflows/tasks have been tested on Terra with a different dataset than used for development
- [x] All reviewer-suggested scenarios have been tested and any additional
- [x] All changed results have been confirmed to be accurate
- [x] All workflows/tasks impacted by change/s have been tested using a standard validation dataset to ensure no unintended change of functionality
- [x] All code adheres to the style guide
- [x] MD5 sums have been updated
- [x] The PR author has addressed all comments

## 🗂️ Associated Documentation (to be completed by Theiagen developer)

- [ ] Relevant documentation on the Public Health Resources "PHB Main" has been updated
- [ ] Workflow diagrams have been updated to reflect changes

### CODE REVIEW

**Comment by michellescribner** [comment]
Add outputs to taxon tables

**Comment by jrotieno** [comment]
Updated the code such that A. baummannii have different outputs for abricate database, version and docker from the optional outputs. The rationale is that now or in the future the abricate database one would want to run as optional might be different from the one run by merlin magic, even for the same pathogen. Also good for testing if the optional output is working correctly when abricate optional uses the same database as merlin magic. If this is unnecessary, happy to revert.

**Review by cimendes — CHANGES_REQUESTED** [review]
In an effort to make this PR more compatible with PR #429 (as well as flu in theiacov), I suggest that in merlin_magic instead of calling the instance for abricate baumanii just abricate, change it to `abricate_baumanii_task.abricate_baumanii` or something similar so that there is less confusion to where a given output is coming from. This basically avoids the question on what abricate is running, is it the "normal" one in the workflow itself (what this PR is adding), or is it abricate in merlin magic, and if so, which of the ones implemented is it?

**Comment by cimendes** [comment]
Retesting Abricate true on _A. Baumannii_ genomes with TheiaProk_FASTA to verify that output names are not conflicting: 
- https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/4b600512-22a8-4c92-9ebf-2008a4734f1d

**Review by cimendes — APPROVED** [review]

**Pull request merged**
