### PR TITLE
Fix bugs in read proportion calculation - read_screen task

### LINKED ISSUE #206: Read screen not matching with PHBG
:bug:

### :pencil: Describe the Issue

According to [this](https://github.com/theiagen/public_health_bacterial_genomics/pull/180/files), the read_screen task should be failing for unbalance for 40% or less. This is as described in our documentation:

image

### :repeat: How to Reproduce

- Was this run on the Terra platform?
  - Terra on GCP or Azure?
- Or were the workflows run locally using `miniwdl` or `cromwell`?
  - **What was the exact command was used to launch the workflow?**
- If possible, we may ask you to share your Terra workspace with us. Usually READER access is sufficient, but we may ask for WRITER access if we need to make changes to the workspace to reproduce the issue.

### :fishing_pole_and_fish: Expected Behavior

The task should be adjusted to reflect the information on the documentation!

### :floppy_disk: Version Information

v1.2.0

### :information_source: Additional Information

Reported by @emmadoughty

### PR DESCRIPTION
**Pull request by cimendes**
Closes #206 

## :hammer_and_wrench: Changes Being Made

The current implementation is not calculating the proportion of reads correctly, and the reported error message doesn't reflect the defined parameter correctly. This has been fixed to reflect the changes made in PHBG https://github.com/theiagen/public_health_bacterial_genomics/pull/180/files

## :brain: Context and Rationale

N/A

## :clipboard: Workflow/Task Steps

N/A 

### Inputs

N/A

### Outputs

N/A

### Locally

Not tested locally.

### Terra

~~Tests underway~~ 

Tested on a mixed sample (not matching forward and reverse read files): https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Scribner_Sandbox/job_history/d894f237-af78-40b2-a5db-52868e3f31c4

image

## :microscope: Quality checks

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The workflow/task has been tested locally and on Terra
- [x] The CI/CD has been adjusted and tests are passing
- [x] Everything follows the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-bb456f34322d4f4db699d4029050481c)

### CODE REVIEW

**Comment by cimendes** [comment]
The proportion of reads calculation has been fixed but the validation on the number of reads has been left unchanged. The documentation has been updated to better reflect that the minimum number of reads is being validated for both forward and reverse read files.
image

**Comment by cimendes** [comment]
Testing on sample ERR1015294 that should fail read_screen: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/48713209-6087-4e0d-8ae1-fec713d6c3db

**Comment by sage-wright** [comment]
Testing here, will approve upon success https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Wright_PHBG_Sandbox/job_history/5cfb4437-788b-47f4-b942-568791eeb044

**Review by sage-wright — APPROVED** [review]
Fantastic catch & wonderful math! 🎉

**Pull request merged**
