### PR TITLE
[theiacov_illumina wfs] Output aligned FASTQs without supplemental/secondary alignments

### LINKED ISSUE #544: theiacov_illumina wf: aligned FASTQ files may contain duplicate FASTQ entries
:bug:

### :pencil: Describe the Issue

A user notified us that upon submitting aligned FASTQ files, produced by the TheiaCoV_Illumina_PE workflow, to SRA, NCBI noticed there was at least one occurrence of having identical read headers present in the same FASTQ file (R2 aligned FASTQ file, specifically)

The first read appears to be a shortened & likely hardclipped read that had the same identifier as a second read, which was the original, full length read produced by the sequencer. I confirmed this by searching the original input FASTQ file.

This occurred with an Mpox sample, but could potentially occur with any organism that uses the standard iVar track of the workflow.

### :repeat: How to Reproduce

- Was this run on the Terra platform?
  - Terra on GCP or Azure? GCP
- Or were the workflows run locally using `miniwdl` or `cromwell`? **N/A**
  - **What was the exact command was used to launch the workflow?**
- If possible, we may ask you to share your Terra workspace with us. Usually READER access is sufficient, but we may ask for WRITER access if we need to make changes to the workspace to reproduce the issue.

### :fishing_pole_and_fish: Expected Behavior

There should not be duplicated read IDs present in output aligned FASTQ files. I'm not sure which of the 2 reads should be kept, but may have an idea after learning more about the hardclipped read and how well the original read aligned to the reference.

### :floppy_disk: Version Information

Need to double check which version was used, but likely a recent one.

### PR DESCRIPTION
**Pull request by kapsakcj**
This PR closes #544

🗑️ This dev branch should NOT be deleted after merging to main. One PHL partner may use the dev branch after merging to `main`

## :brain: Summary

This PR updates the bwa task used in TheiaCoV_illumina workflows (i.e. ivar consensus subworkflow) to create a new & separate BAM file that only includes aligned reads. This BAM is not an output file, but is simply used to extract aligned FASTQ files which are output file(s).

The new flag `samtools view -F 0x904` excludes unaligned, secondary, and supplementary reads: `0x904 = 4 (unaligned) + 100 (secondary) + 800 (supplementary)`. See here for complete description of samtools filtering parameters: https://www.htslib.org/doc/samtools.html#FILTER_EXPRESSIONS:~:text=of%20the%20category.-,flags,-samtools%20flags%20INT

This will allow for the output aligned FASTQ files to ONLY contain aligned reads and prevent inclusion of supplementary alignments, which were noticed upon submission to NCBI SRA due to duplicate FASTQ headers.

## :zap: Impacted Workflows/Tasks

This change impacts workflows that call the `bwa` task, so the ivar_consensus subworkflow which is used in:

- Theiacov_illumina_PE
- theiacov_illumina_se
- theiameta_illumina_pe (which does output aligned reads)
- freyja_fastq (which does NOT output aligned reads, so freyja_fastq is only indirectly affected by this change)

This PR may lead to different results in pre-existing outputs: **Yes, aligned FASTQ files may be smaller due to secondary & supplementary alignments being excluded**

This PR uses an element that could cause duplicate runs to have different results: **No**

### :gear: Algorithm

N/A

### ➡️ Inputs

N/A

### ⬅️ Outputs

Yes, the `bwa` task outputs `read1_aligned` and `read2_aligned` File outputs will be different than before (pending that supplementary and/or secondary alignments were produced by the alignment. This doesn't always happen and sometimes there are very few supplemental alignments (10s for example) compared to total number of reads (100,000's or higher, for example)

## :test_tube: Testing

- Tested extensively with 1 Mpox sample: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-theiagen-validations/job_history/92354634-854c-49b2-9772-492bdcef096a
  - confirmed that output aligned FASTQs have no duplicate FASTQ headers:
```bash
# R1 aligned FASTQ file, no duplicate headers
$ zcat sample01_R1.fastq.gz | grep '^@' | wc -l
227238
$ zcat sample01_R1.fastq.gz | grep '^@' | sort -u | wc -l
227238

# R2 aligned FASTQ file, no duplicate headers
$ zcat sample01_R2.fastq.gz | grep '^@' | sort -u | wc -l
227308
$ zcat sample01_R2.fastq.gz | grep '^@' | wc -l
227308
```

- sars-cov-2 test ILMN PE test: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-theiagen-validations/job_history/3ff1b4db-ef1d-4db6-b09a-4f2ed2fdf24b
  - v2.1.0 wf outputs aligned R1 FASTQ with 1 duplicate FASTQ and R2 FASTQ with 3 duplicate FASTQs
  - ~~⚠️ Need to review output aligned FASTQs to ensure there are no duplicates~~ Confirmed that output read1 & read 2 aligned FASTQ had all unique IDs ✅ 
- sars-cov-2 test ILMN SE test: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-theiagen-validations/job_history/3ff1b4db-ef1d-4db6-b09a-4f2ed2fdf24b
  - same sample as above, so R1 aligned FASTQ output from v2.1.0 wf did have 1 duplicate read present
  - ~~⚠️ Need to review output aligned FASTQ to ensure the duplicate is not present.~~ Confirmed that output read1 aligned FASTQ had all unique IDs ✅ 

### Suggested Scenarios for Reviewer to Test

Test out TheiaMeta_illumina_PE

Also test any theiacov_illumina workflow with any non-Flu organism. Perhaps with WNV validation datasets or other sars-cov-2 samples

## :microscope: Final Developer Checklist

- [x] The workflow/task has been tested and results, including file contents, are as anticipated
- [x] The CI/CD has been adjusted and tests are passing (Theiagen developers)
- [x] Code changes follow the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-51b66a47dde54c798f35d673fff80249)
- [x] Documentation and/or workflow diagrams have been updated if applicable (Theiagen developers only)

## 🎯 Reviewer Checklist

- [x] All changed results have been confirmed
- [x] You have tested the PR appropriately (see the [testing guide](https://theiagen.notion.site/PR-Testing-Guide-Determining-Appropriate-Levels-of-Testing-4764e98a6aeb460185039c0896714590) for more information)
- [x] All code adheres to the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-51b66a47dde54c798f35d673fff80249)
- [x] MD5 sums have been updated
- [x] The PR author has addressed all comments
- [x] The documentation has been updated

### CODE REVIEW

**Comment by kapsakcj** [comment]
Testing Theiameta_illumina_pe here on 1 sample, just to ensure it's unimpacted: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-theiagen-validations/job_history/3971892a-a9d0-4754-a0c8-edcea1edab76

No need for you to test @cimendes ! Appreciate the offer though. I forgot I had data accessible to test with

**Review by sage-wright — COMMENTED** [review]
Code changes look good, will approve upon successful test completion [here](https://app.terra.bio/#workspaces/theiagen-validations/sage_viral/job_history/ccf1ab9f-ee14-4f02-bd79-65203bb58063)

**Review by sage-wright — APPROVED** [review]
Phenomenal work, Curtis

**Comment by cimendes** [comment]
@kapsakcj can this branch be deleted?

**Comment by kapsakcj** [comment]
No, let's keep it for now and I'll check in with our user to see if they still need it. Will also mention they can use the `main` branch.

I'll delete it when we're ready

**Pull request merged**
