### PR TITLE
[TheiaCoV_Illumina_PE & _ONT] Create sub-workflow for flu-specific modules

### LINKED ISSUE #409: [TheiaCoV] Isolate nextclade_v3 task for flu so that we can have outputs for HA and NA segments clearly identified
:cool:

### :pushpin: Explain the Request

Currently the nextclade outputs for flu only identify in the name of the segment for NA. For HA everything gets populated to the data table as just `nexclade_tsv` or `nextclade_clade`. It would be super helpful for the user to know that these refer to the HA segment. 

This could be done by creating a third call of nextclade within theiacov, therefore having a nextclade call for all single-segment viruses (sc2, mpox, rsv-a, rsv-b) and have isolated for flu a nextclade_ha and nextclade_na.

### PR DESCRIPTION
**Pull request by sage-wright**
This PR closes #409.

*** Merge after PR #468 

🗑️ This dev branch should be deleted after merging to main.

## :brain: Aim, Context and Functionality

Flu is a different beast due to its segmentation. The amount of flu-specific modules were growing to consume most of the workflow files for TheiaCoV_Illumina_PE and _ONT. In addition, the Nextclade outputs for HA did not have the _HA suffix, which led to confusion. 

## :hammer_and_wrench:  Impacted Workflows/Tasks & Changes Being Made
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : Yes but no

Outputs will remain the same, but the processing of the flu-specific tasks will occur in a different subworkflow

Running this workflow on different occasions could result in different results, e.g. due to use of a live database, "latest" docker image, or stochastic data processing : No 

The following tasks were moved to the `flu_track` subworkflow:
- IRMA
- assembly statistics for the HA & NA segments
- `abricate_flu`
- Nextclade for both the NA & HA segment
  - the nextclade output parser task for each segment as well
- the `flu_antiviral_substitutions` subworkflow

#### 🔄 Data Processing 

Docker/software or software versions changed: 

- No changes

Databases or database versions changed:

- No changes

Data processing/commands changed:

- Consolidates multiple modules into a single subworkflow
  - all task options are still available for user modification
   
File processing changed:

- No changes

Compute resources changed:

- No changes

#### ➡️ Inputs 

- Flu-specific input parameters appear under the `flu_track` task instead of the respective task name

#### ⬅️ Outputs 

New outputs:
- `File? nextclade_json_flu_ha`
- `File? auspice_json_flu_ha`
- `File? nextclade_tsv_flu_ha`
- `String? nextclade_ds_tag_flu_ha`
- `String? nextclade_aa_subs_flu_ha`
- `String? nextclade_aa_dels_flu_ha`
- `String? nextclade_clade_flu_ha`
- `File? nextclade_json_flu_na`
- `File? auspice_json_flu_na`
- `File? nextclade_tsv_flu_na`
- `String? nextclade_ds_tag_flu_na`
- `String? nextclade_aa_subs_flu_na`
- `String? nextclade_aa_dels_flu_na`
- `String? nextclade_clade_flu_na`

Changed outputs:
- All outputs from Nextclade _without_ a _flu_* suffix are NON-FLU outputs
  - Nextclade_version and Nextclade_docker are the exceptions

#### Terra Testing

ONT test [here](https://app.terra.bio/#workspaces/theiagen-validations/sage_viral/job_history/ad446856-a114-4e79-8a68-b74c81400f78) with various organisms]
Illumina PE test [here](https://app.terra.bio/#workspaces/theiagen-validations/sage_viral/job_history/d67e2d17-433c-41b3-9f64-adc809bf848c) with various organisms

#### Suggested Scenarios for Reviewer to Test

- flu
- non-flu

## :microscope: Final Developer Checklist

- [x] The workflow/task has been tested locally and results, including file contents, are as anticipated
- [x] The workflow/task has been tested on Terra and results, including file contents, are as anticipated
- [x] The CI/CD has been adjusted and tests are passing (to be completed by Theiagen developer)
- [x] Code changes follow the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-bb456f34322d4f4db699d4029050481c)

## 🎯 Reviewer Checklist 

- [x] All impacted workflows/tasks have been tested on Terra with a different dataset than used for development
- [x] All reviewer-suggested scenarios have been tested and any additional
- [x] All changed results have been confirmed to be accurate
- [x] All workflows/tasks impacted by change/s have been tested using a standard validation dataset to ensure no unintended change of functionality
- [x] All code adheres to the style guide
- [x] MD5 sums have been updated
- [x] The PR author has addressed all comments

## 🗂️ Associated Documentation (to be completed by Theiagen developer)

- [x] Relevant documentation on the Public Health Resources "PHB Main" has been updated
- [x] Workflow diagrams have been updated to reflect changes

### CODE REVIEW

**Comment by cimendes** [comment]
Reviewing after #468 is merged

**Comment by kapsakcj** [comment]
My tests here, still need to review outputs:

- ILMN PE: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-theiagen-validations/job_history/0e8c3f81-c338-488f-b62a-f3eb52a66c56
- ONT: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-theiagen-validations/job_history/3a52b0ca-ce03-47ca-a72d-b9534bece164

**Comment by kapsakcj** [comment]
Curtis TODOs:

- [ ] update workflow diagram - no longer just tamiflu, state "antiviral" instead of "tamiflu" in the orange block on left side of theiacov diagram
- [ ] update PHB Main docs

**Review by kapsakcj — APPROVED** [review]
Code changes look good.

Docs - I've updated TheiaCoV inputs, but need to double check on theiacov outputs to make sure they are still accurate. Will merge when I'm finished

**Pull request merged**
