### PR TITLE
expose optional input parameter disk_size for kraken2 standalone wfs

### LINKED ISSUE #315: [feature request] expose disk_size optional input for kraken workflows
:cool:

### :pushpin: Explain the Request

`disk_size` is not exposed as an optional input parameter in the kraken2_PE_PHB and kraken2_SE_PHB workflows. A user ran into disk space issues/errors using this workflow with large databases and has no way of requesting a VM with a larger disk.

### :books: Context

see above

### :chart_with_upwards_trend: Desired Behavior

Allow user to optionally define `disk_size` for the kraken2 task within the 2 aforementioned workflows.

### :information_source: Additional Information

I've started a dev branch called `cjk-kraken-standalone-disk-size` to address this request & have started testing in Terra. I'll open a draft PR momentarily

### PR DESCRIPTION
**Pull request by kapsakcj**
This PR closes #315 

🗑️ This dev branch should be deleted after merging to main.

## :brain: Aim, Context and Functionality

[copied from GH issue] 
> `disk_size` is not exposed as an optional input parameter in the kraken2_PE_PHB and kraken2_SE_PHB workflows. A user ran into disk space issues/errors using this workflow with large databases and has no way of requesting a VM with a larger disk.

## :hammer_and_wrench:  Impacted Workflows/Tasks & Changes Being Made
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version: **No**

Running this workflow on different occasions could result in different results, e.g. due to use of a live database, "latest" docker image, or stochastic data processing : **No** 

This code change affects both standalone kraken2 workflows:
- kraken2_PE_PHB 
- kraken2_SE_PHB
- TheiaMeta_Illumina_PE_PHB (**I missed this previously. Didn't realize TheiaMeta calls this task!**)

#### 🔄 Data Processing 

Nothing has changed about the way the workflow runs

Docker/software or software versions changed: **No**

Databases or database versions changed: **No**

Data processing/commands changed: **No**

File processing changed: **No**

Compute resources changed: **Yes, user can now alter disk_size from the default of `100` GB**

#### ➡️ Inputs 

None

#### ⬅️ Outputs 

None

#### Test Dataset

tested on one ILMN PE bacterial sample (see link to test Terra workflow below), and requested `500` as the `disk_size` for the task, and Terra/cromwell did use a VM with a disk size of 500 GB 👍 

#### Commandline Testing with MiniWDL or Cromwell (optional)

Unnecessary, only test in Terra.

#### Terra Testing
successful workflow here: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-theiagen-validations/job_history/dccf8cf5-ab64-4df6-bad8-9cbdd9fd718f

proof that the VM used a 500GB disk:
image

#### Suggested Scenarios for Reviewer to Test

Would be good to test out with large kraken2 databases. My test uses the "kraken2 standard" database which is 38GB compressed and estimated 70-ish GB when uncompressed.

#### Theiagen Version Release Testing (optional)

- Will changes require functional or validation testing (checking outputs etc) during the release? **functional testing**
- Do new samples need to be added to validation datasets? If so, upload these to the appropriate validation workspace Google bucket (). Please describe the new samples here and why these have been chosen. **No**
- Are there any output files that should be checked after running the version release testing? **No**

## :microscope: Final Developer Checklist

- [x] The workflow/task has been tested locally and results, including file contents, are as anticipated
- [x] The workflow/task has been tested on Terra and results, including file contents, are as anticipated
- [x] The CI/CD has been adjusted and tests are passing (to be completed by Theiagen developer)
- [x] Code changes follow the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-bb456f34322d4f4db699d4029050481c)

## 🎯 Reviewer Checklist 

- [x] All impacted workflows/tasks have been tested on Terra with a different dataset than used for development
- [x] All reviewer-suggested scenarios have been tested and any additional
- [x] All changed results have been confirmed to be accurate
- [x] All workflows/tasks impacted by change/s have been tested using a standard validation dataset to ensure no unintended change of functionality
- [x] All code adheres to the style guide
- [x] MD5 sums have been updated
- [x] The PR author has addressed all comments

## 🗂️ Associated Documentation (to be completed by Theiagen developer)

- [x] Relevant documentation on the Public Health Resources "PHB Main" has been updated
- [x] Workflow diagrams have been updated to reflect changes

### CODE REVIEW

**Comment by kapsakcj** [comment]
Reminder: tag Ines when ready for review

**Comment by kapsakcj** [comment]
Just realized that this change also impacts the readQC subworkflows as well...

```
workflows/utilities/wf_read_QC_trim_pe.wdl
workflows/utilities/wf_read_QC_trim_se.wdl:
```

both of these subworkflows call the `kraken2_standalone` task located in `tasks/taxon_id/task_kraken2.wdl`

so I'll run at least one theiaprok_illumina_PE_PHB workflow with the `call_kraken` boolean enabled

**Comment by kapsakcj** [comment]
and just realized that I have to add this option to the read_QC subworkflows as well....

commit incoming. Maybe hold off on the review for a moment

**Comment by kapsakcj** [comment]
OK here's a theiaprok_illumina_pe_PHB test where I set the new optional inputs (for read_QC_pe subworkflow) `kraken_disk_size` to 500 and `kraken_memory` to 64: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-theiagen-validations/workflows/theiagen-validations/TheiaProk_Illumina_PE_PHB

**Comment by kapsakcj** [comment]
and here's a test with TheiaProk_Illumina_SE_PHB with `kraken_disk_size` set to 250 and `kraken_memory` set to 64: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-theiagen-validations/job_history/3ed3bae5-ba78-47d1-b75b-1c99131fdeda

**Comment by cimendes** [comment]
**TheiaMeta_Illumina_PE:**

New input variables are present as expected:
image

✅ Run test successful: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/24bbace4-3074-4c66-883c-aa2fba93bfaf

**Comment by cimendes** [comment]
Kraken2_PE:

New input parameter present as expected:
image

✅ Successful run: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/785c725e-8d55-4327-9bc8-a324b5ec2ad5

**Comment by cimendes** [comment]
Last but not least, documentation!!

- All changes are present on the PHB main documentation page 🌟 
  - ✅ Added TheiaProk
  - ✅ Added TheiaMeta

**Comment by cimendes** [comment]
All is looking good! Great job! I'm approving the PR!

**Review by cimendes — APPROVED** [review]
image

**Pull request merged**
