### PR TITLE
[TheiaProk] Enable plasmidfinder to be skipped 

### LINKED ISSUE #280: Make Plasmidfinder optional, on by default
:bug:

A collaborator reported repeated TheiaProk failures for Enterococcus samples at the plasmidfinder task: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Scribner_Sandbox/job_history/6d7a5682-0e30-44b7-8d66-8b9eac45bbf0

Cause of the issue is not clear to me. The same assembly run through the PlasmidFinder webtool successfully finished and detected plasmids but took several days to run. 

### :repeat: How to Reproduce

- Was this run on the Terra platform?
  - Terra on GCP or Azure?
- Or were the workflows run locally using `miniwdl` or `cromwell`?
  - **What was the exact command was used to launch the workflow?**
- If possible, we may ask you to share your Terra workspace with us. Usually READER access is sufficient, but we may ask for WRITER access if we need to make changes to the workspace to reproduce the issue.

### LINKED ISSUE #359: disable call caching for rasusa standalone workflow
:cool:

### LINKED ISSUE #370: [BaseSpace_Fetch] hide preemptible input parameter
:bug:

It's currently set to 1 whereas for every other task we use 0 (do not request preemptible VMs). Should we also change this default? 

For context:
- https://support.terra.bio/hc/en-us/articles/360029772212-Controlling-Google-Cloud-costs-sample-use-cases
- https://cromwell.readthedocs.io/en/stable/RuntimeAttributes/#preemptible

### :repeat: How to Reproduce

- Was this run on the Terra platform?
  - Terra on GCP or Azure?
- Or were the workflows run locally using `miniwdl` or `cromwell`?
  - **What was the exact command was used to launch the workflow?**
- If possible, we may ask you to share your Terra workspace with us. Usually READER access is sufficient, but we may ask for WRITER access if we need to make changes to the workspace to reproduce the issue.

### PR DESCRIPTION
**Pull request by sage-wright**
This PR closes #280, closes #370 and closes #359.

🗑️ This dev branch should be deleted after merging to main.

## :brain: Aim, Context and Functionality

This PR does three things:
1. Provides a user input for users to turn off plasmidfinder
2. Hides the preemptible input parameter for BaseSpace_Fetch (no testing required except for checking the inputs of the workflow on Terra)
3. Disables call caching on RASUSA 

## :hammer_and_wrench:  Impacted Workflows/Tasks & Changes Being Made
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : Yes (call caching off on RASUSA)

Running this workflow on different occasions could result in different results, e.g. due to use of a live database, "latest" docker image, or stochastic data processing : Yes (RASUSA is random, but we only want to test to see if call caching is actually off

- volatile: true is added to the RASUSA meta field
- the new input parameter `call_plasmidfinder` (default=`true`) is added to all TheiaProk workflows
- preemptible is now hard-coded in the BaseSpace_Fetch task to the default preemptible value of 1

#### 🔄 Data Processing 
 No

Docker/software or software versions changed: No

Databases or database versions changed: No

Data processing/commands changed: No

File processing changed: No

Compute resources changed:
- preemptible is now hard-coded to 1 in BaseSpace_Fetch
- volatile:true turns off call caching in RASUSA

#### ➡️ Inputs 

TheiaProk workflows now have the `call_plasmidfinder` optional workflow input. True by default, no change will be noticed by users of TheiaProk unless they set the value of that variable to false.

#### Terra Testing

- [x] preemptible is no longer an input in BaseSpace_Fetch when compared to v1.3.0
- [x] RASUSA did not use call caching (view [initial run here](https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Wright_PHBG_Sandbox/job_history/a0714299-049d-4af3-b469-df6739ecd2ad) and [running it again to test call-cache off test here](https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Wright_PHBG_Sandbox/job_history/39e45570-2e53-4df5-8680-4a24661f6c19)
- [ ] PlasmidFinder turned on and off
  - [ ] [TheiaProk_Illumina_PE here](https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Wright_PHBG_Sandbox/job_history/9ee910fc-c02b-414c-84a4-7a40da05f988)
  - [ ] [TheiaProk_Illumina_SE here](https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Wright_PHBG_Sandbox/job_history/a82d3ff4-d345-4dbc-b897-37f2be6253a1)
  - [ ] [TheiaProk_ONT here](https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Wright_PHBG_Sandbox/job_history/d5d7fbbe-9676-4422-8c20-c505585f22a5)
  - [x] [TheiaProk_FASTA here](https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Wright_PHBG_Sandbox/job_history/2f5eb14c-ee9c-47dc-90e2-1bc31200b0e4)

#### Theiagen Version Release Testing (optional)

- New plasmidfinder input variable field with various set to true & false will need to be added to the validation table

## :microscope: Final Developer Checklist

- [x] The workflow/task has been tested locally and results, including file contents, are as anticipated
- [x] The workflow/task has been tested on Terra and results, including file contents, are as anticipated
- [x] The CI/CD has been adjusted and tests are passing (to be completed by Theiagen developer)
- [x] Code changes follow the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-bb456f34322d4f4db699d4029050481c)

## 🎯 Reviewer Checklist 

- [x] All impacted workflows/tasks have been tested on Terra with a different dataset than used for development
- [x] All reviewer-suggested scenarios have been tested and any additional
- [ ] All changed results have been confirmed to be accurate
- [ ] All workflows/tasks impacted by change/s have been tested using a standard validation dataset to ensure no unintended change of functionality
- [x] All code adheres to the style guide
- [x] MD5 sums have been updated
- [ ] The PR author has addressed all comments

## 🗂️ Associated Documentation (to be completed by Theiagen developer)

- [ ] Relevant documentation on the Public Health Resources "PHB Main" has been updated
- [x] ~Workflow diagrams have been updated to reflect changes~ NA

### CODE REVIEW

**Review by cimendes — CHANGES_REQUESTED** [review]
Can we change rasusa's wf input of genome length from string to int?

**Comment by sage-wright** [comment]
[As per the tool documentation](https://github.com/mbhall88/rasusa?tab=readme-ov-file#-g---genome-size), genome length can be either an integer or have a metric suffix, so I think we should keep it as a String

**Comment by cimendes** [comment]
Given the general context of PHB, we always set the genome length as int so I think it would be easier to document and transmit to our users the same standard! What do you think?

**Comment by sage-wright** [comment]
I think that warrants further discussion! @kapsakcj and @jrotieno, any opinions?

**Comment by kapsakcj** [comment]
I would prefer to keep it as a String because of what Rasusa can accept (and the usage is bit more flexible this way)

Plus we have documentation surrounding the use of strings like `5m` for this particular workflow

And there are users who are now accustomed to providing these strings as input

**Comment by jrotieno** [comment]
On one hand I am thinking String is versatile to allow both a string and integer input, while on the other I am not sure that we want to encourage people to input 5Kb instead of 5000 even if the tool allows it.

**Comment by cimendes** [comment]
I guess this settles it! It shall remain as is! :D Approving the PR and merging!

**Review by cimendes — APPROVED** [review]

**Pull request merged**
