### PR TITLE
Use docker images stored in Google Artifact Register 

### PR DESCRIPTION
**Pull request by andrewjpage**
## :hammer_and_wrench: Changes Being Made
All docker images have been copied from quay.io/dockerhub to Google Artifact Register with the exception of some standard ones like 'ubuntu' or python slim.

## :brain: Context and Rationale
Please be aware that old forks will point to the original images on quay.io/dockerhub and will need to be updated, or rebased on to this PR.
The rational for this is that we need to control images and specific versions so that we have control over them for validation. Public images not under our control could be deleted and break a validated workflow.
Additionally there have been some technical issues with some of the public hosting sites. These images are hosted in the GCP multi-region (US) which is where virtually all Terra VMs run from, giving more reliability, lower latency and free network ingress/egress.
The easiest way to add a new image is to pull to a VM with docker, then push to GAR. 
```
# Login to Google Cloud
gcloud auth configure-docker us-docker.pkg.dev

# Build the docker image locally for GCP
docker build -t us-docker.pkg.dev/general-theiagen/theiagen/myapp:1.2.3 myapp:1.2.3

# Push the docker image to GCP
docker push us-docker.pkg.dev/general-theiagen/theiagen/myapp:1.2.3
```

## :test_tube: Testing

This will need testing with TheiaValidate.

### Terra
https://app.terra.bio/#workspaces/theiagen-validations/page_sandbox/job_history/589dea57-2506-4824-924e-917fac762907

## :microscope: Quality checks

Pull Request (PR) checklist:
- [ x] Include a description of what is in this pull request in this message.
- [ x] The workflow/task has been tested locally and on Terra
- [x ] Everything follows the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-bb456f34322d4f4db699d4029050481c)

### CODE REVIEW

**Comment by sage-wright** [comment]
Shigeifinder 1.3.5 is not in the registry -- we're adding it now

**Comment by sage-wright** [comment]
The new NCBI read scrubber docker is causing failures -- it's a newer version than the one we currently have in main and has different output files. We're adding the version we're had been using to the artifact registry and making that change in the code.

**Comment by kapsakcj** [comment]
Sage & I ran TheiaValidate workflow on the main TheiaCov & TheiaProk workflows. The PDF reports & identified differences XLSX files can be viewed in the `validations` data table. https://app.terra.bio/#workspaces/theiagen-validations/PHB_Validation_v1-0-0_artifact_registry/data

No major unexpected differences were found when running workflows using PHB v1.0.0 with non-google-artifact-registry hosted docker images vs PHB v1.0.1 (impending release) that use GAR-hosted docker images 🎉 

There were some minor Flu-related and TheiaEuk differences between the 2 but those were caused by differences in nextclade_dataset_tag's and contig ordering. No major concerns

**Comment by kapsakcj** [comment]
Once the automated tests pass & any other CI hashes are updated. I'm good to merge 👍

**Review by kapsakcj — APPROVED** [review]

**Pull request merged**
