### PR TITLE
Fix Empty Mean Coverage for Flu HA and NA Assemblies

### LINKED ISSUE #361: [TheiaCoV_Illumina_PE] assembly_mean_coverage  always being reported as empty for flu samples
:bug:

### :pencil: Describe the Issue

The values in this validation show the result of assembly_mean_coverage always as `HA: , NA: ` for all flu samples.
https://app.terra.bio/#workspaces/theiagen-validations/PHB_Validation_PR_310 -> `theiacov_illumina_pe` data table

### PR DESCRIPTION
**Pull request by jrotieno**
This PR closes #361.

🗑️ This dev branch should <NOT> be deleted after merging to main.

## :brain: Aim, Context and Functionality

This PR fixes an issue with empty mean coverage estimates for influenza HA and Na assemblies.
## :hammer_and_wrench:  Impacted Workflows/Tasks & Changes Being Made

This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : Yes

Running this workflow on different occasions could result in different results, e.g. due to use of a live database, "latest" docker image, or stochastic data processing : Yes, but not due to this change

#### 🔄 Data Processing 

Docker/software or software versions changed: No

Databases or database versions changed: No

Data processing/commands changed: Yes, to correctly capture BAM files used to calculate assembly coverage

File processing changed: No

Compute resources changed: No

#### ➡️ Inputs 

No changes

#### ⬅️ Outputs 

No changes

#### Test Dataset

Tested using a set of 11 influenza sample reads, including one that is simulated data.

#### Commandline Testing with MiniWDL or Cromwell (optional)

Tested the irma task locally and worked as expected.

#### Terra Testing

https://app.terra.bio/#workspaces/cdph-terrabio-taborda-manual/Global_tree_testing/job_history/ffe75b13-4dde-4c51-af39-bd5215058b0e

## :microscope: Final Developer Checklist

- [x] The workflow/task has been tested locally and results, including file contents, are as anticipated
- [x] The workflow/task has been tested on Terra and results, including file contents, are as anticipated
- [x] The CI/CD has been adjusted and tests are passing (to be completed by Theiagen developer)
- [x] Code changes follow the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-bb456f34322d4f4db699d4029050481c)

## 🎯 Reviewer Checklist 

- [x] All impacted workflows/tasks have been tested on Terra with a different dataset than used for development
- [x] All reviewer-suggested scenarios have been tested and any additional
- [x] All changed results have been confirmed to be accurate
- [x] All workflows/tasks impacted by change/s have been tested using a standard validation dataset to ensure no unintended change of functionality
- [x] All code adheres to the style guide
- [x] MD5 sums have been updated
- [x] The PR author has addressed all comments

## 🗂️ Associated Documentation (to be completed by Theiagen developer)

- [ ] Relevant documentation on the Public Health Resources "PHB Main" has been updated
- [ ] Workflow diagrams have been updated to reflect changes

### CODE REVIEW

**Comment by cimendes** [comment]
@jrotieno Two samples failed on your test dataset that I believe are related to this PR! The irma error is as follows:

> Sample_01_HA.fasta
> Sample_01_NA.fasta
> mv: 'Sample_01_HA.bam' and 'Sample_01_HA.bam' are the same file
> mv: 'Sample_01_NA.bam' and 'Sample_01_NA.bam' are the same file

Can you take a look? 

I've launched a second test at https://app.terra.bio/#workspaces/theiagen-validations/PHB_Validation_PR_310/job_history/7e6d16c7-bb81-4a6c-aa02-408d1335427f on 21 FLU samples

**Comment by cimendes** [comment]
Good news! In some samples, the outputs look as expected:

(sample_id, assembly_length, assembly_mean_coverage)
image

In others, only one of the fragments was recovered:
image

And in others, despite the assembly having content and the fragments being recovered by IRMA, the output is still empty:
image
image

**Comment by jrotieno** [comment]
@cimendes the samples without assembly mean coverage were not part of the 21 you ran in https://app.terra.bio/#workspaces/theiagen-validations/PHB_Validation_PR_310/job_history/7e6d16c7-bb81-4a6c-aa02-408d1335427f. I am re-running the ones with previous assemblies: https://app.terra.bio/#workspaces/theiagen-validations/PHB_Validation_PR_310/job_history/b440f1c8-f6a5-4f1c-9716-756e579cad97

**Comment by cimendes** [comment]
Status update: Waiting on feedback for the two failures in https://app.terra.bio/#workspaces/cdph-terrabio-taborda-manual/Global_tree_testing/job_history/ffe75b13-4dde-4c51-af39-bd5215058b0e

**Comment by jrotieno** [comment]
Good to go @cimendes

**Comment by cimendes** [comment]
Relaunching test with Flu B here: https://app.terra.bio/#workspaces/cdph-terrabio-taborda-manual/Global_tree_testing/job_history/b2ed1f54-b0ae-4f9d-88e7-69801c76d457

**Comment by cimendes** [comment]
Code changes look good! Will approve and merge as soon as the test is successful :)

**Review by cimendes — APPROVED** [review]

**Pull request merged**
