### PR TITLE
Snippy Gene Query fixes

### LINKED ISSUE #99: Snippy gene query product names are truncated if they contain commas
### The snippy gene query task has the following steps:

1. queries the variant calling output for query strings
2. saves the rows with those strings to a csv
3. parses the csv to save the product name and mutation to a variable

If the product name contains a comma, it interferes with step 3 and causes the product name to be truncated.

### Example: 
For the mutation below, the product should be shown as "1,3-beta-glucan synthase component FKS1" in the theiaeuk_snippy_variant_hits output, but is instead truncated to just "1".

</head>

<body link="#0563C1" vlink="#954F72">

CHROM | POS | TYPE | REF | ALT | EVIDENCE | FTYPE | STRAND | NT_POS | AA_POS | EFFECT | LOCUS_TAG | GENE | PRODUCT
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
PEKT02000002 | 1006622 | snp | A | C | C:53 A:0 | CDS | - | 1918/5667 | 640/1888 | missense_variant c.1918T>G p.Leu640Val | B9J08_000964 | - | 1,3-beta-glucan synthase component FKS1

</body>

</html>

### PR DESCRIPTION
**Pull request by sage-wright**
Closes #99 

## :hammer_and_wrench: Changes Being Made

- Adjusts snippy_gene_query to not truncate items that include commas (described in #99)
- Encloses the `~{validation_criteria_tsv}` variable in quotes in TheiaValidate

## :brain: Context and Rationale

The snippy_gene_query change prevents incomplete results; the variable quoting prevents workflow failure.

## :clipboard: Workflow/Task Steps

No change

### Inputs

No change

### Outputs

No change

### Locally

Tests were successful.

### Terra

Testing for snippy_gene_query ongoing here: 
- https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Wright_PHBG_Sandbox/job_history/914afcd7-7e73-4fa7-aa0c-57c5cfccc449
- https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Wright_PHBG_Sandbox/job_history/73007c8b-5759-4518-b22c-e45dd25a6d15

Test for the TheiaValidate bug fix can be found here: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Wright_PHBG_Sandbox/job_history/83e229c0-7dd2-4000-96c3-2ba9caa04877

## :microscope: Quality checks

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The workflow/task has been tested locally and on Terra
- [x] The CI/CD has been adjusted and tests are passing
- [x] Everything follows the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-bb456f34322d4f4db699d4029050481c)

### CODE REVIEW

**Comment by michellescribner** [comment]
Tested TheiaEuk snippy gene query bug fix here: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Scribner_Sandbox/job_history/f6ad89bf-0648-413a-8125-596ff4006778

**Review by michellescribner — DISMISSED** [review]
Looks great! Ready to merge once GHA checks pass

**Comment by sage-wright** [comment]
omg I'm going crazy I keep getting confused on what branch I'm on. FYI, I do not recommend trying to fix the CI for two separate branches at the same time haha

**Comment by sage-wright** [comment]
@michellescribner  -- tests are now passing! 🎉

**Review by kevinlibuit — APPROVED** [review]

**Pull request merged**
