### PR TITLE
[Style Guide] Semantic adjustments throughout the PHB universe

### LINKED ISSUE #365: [read_QC_trim] trim_minlen -> trim_minlength to respect new style-guide
:bug:

### :repeat: How to Reproduce

- Was this run on the Terra platform?
  - Terra on GCP or Azure?
- Or were the workflows run locally using `miniwdl` or `cromwell`?
  - **What was the exact command was used to launch the workflow?**
- If possible, we may ask you to share your Terra workspace with us. Usually READER access is sufficient, but we may ask for WRITER access if we need to make changes to the workspace to reproduce the issue.

### LINKED ISSUE #366: [read_QC_trim] trim_quality_trim_score -> trim_quality_min_score
:bug:

### :repeat: How to Reproduce

- Was this run on the Terra platform?
  - Terra on GCP or Azure?
- Or were the workflows run locally using `miniwdl` or `cromwell`?
  - **What was the exact command was used to launch the workflow?**
- If possible, we may ask you to share your Terra workspace with us. Usually READER access is sufficient, but we may ask for WRITER access if we need to make changes to the workspace to reproduce the issue.

### LINKED ISSUE #367: [QUAST] min_contig_len -> min_contig_length as per style guide
:bug:

Additionally cpu, memory and disk_size are not exposed

### :repeat: How to Reproduce

- Was this run on the Terra platform?
  - Terra on GCP or Azure?
- Or were the workflows run locally using `miniwdl` or `cromwell`?
  - **What was the exact command was used to launch the workflow?**
- If possible, we may ask you to share your Terra workspace with us. Usually READER access is sufficient, but we may ask for WRITER access if we need to make changes to the workspace to reproduce the issue.

### LINKED ISSUE #368: [VADR] maxlen -> maxlength and minlen -> minlength as per style-guide
:bug:

### :repeat: How to Reproduce

- Was this run on the Terra platform?
  - Terra on GCP or Azure?
- Or were the workflows run locally using `miniwdl` or `cromwell`?
  - **What was the exact command was used to launch the workflow?**
- If possible, we may ask you to share your Terra workspace with us. Usually READER access is sufficient, but we may ask for WRITER access if we need to make changes to the workspace to reproduce the issue.

### PR DESCRIPTION
**Pull request by cimendes**
This PR closes #365 and closes #366 and closes #367 and closes #368.

🗑️ This dev branch should <NOT> be deleted after merging to main.

## :brain: Aim, Context and Functionality

This PR aims to harmonize a few inputs in workflows and sub-workflows to better adhere to our style-guide!

## :hammer_and_wrench:  Impacted Workflows/Tasks & Changes Being Made
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : No, it changes only input parameters. Default JSON inputs will need to be updated

Running this workflow on different occasions could result in different results, e.g. due to use of a live database, "latest" docker image, or stochastic data processing : No 

Please see `Files changed` for an exhaustive list of all the inputs that were adjusted!

#### 🔄 Data Processing 

Docker/software or software versions changed: None

Databases or database versions changed: None

Data processing/commands changed: None

File processing changed: None

Compute resources changed: None

#### ➡️ Inputs 

- minlen -> min_length
- maxlen -> max_length
- min_contig_len -> min_contig_length
- fastp_minlen -> fastp_min_length
- trimmomatic_minlen -> trimmomatic_min_length
- trim_quality_trim_score -> trim_quality_min_score
- min_contig_len -> min_contig_length

#### ⬅️ Outputs 

None

#### Commandline Testing with MiniWDL or Cromwell (optional)

Skipped in favour if testing in Terra!

#### Terra Testing

In the comments below!

#### Suggested Scenarios for Reviewer to Test

- All the theiacovs except for theiacov_fasta_batch
- Freyja
- TheiaMeta
- TheiaEuk
- TheiaProk_illumina SE and PE

## :microscope: Final Developer Checklist

- [ ] The workflow/task has been tested locally and results, including file contents, are as anticipated
- [x] The workflow/task has been tested on Terra and results, including file contents, are as anticipated
- [x] The CI/CD has been adjusted and tests are passing (to be completed by Theiagen developer)
- [x] Code changes follow the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-bb456f34322d4f4db699d4029050481c)

## 🎯 Reviewer Checklist 

- [x] All impacted workflows/tasks have been tested on Terra with a different dataset than used for development
- [x] All reviewer-suggested scenarios have been tested and any additional
- [x] All changed results have been confirmed to be accurate
- [x] All workflows/tasks impacted by change/s have been tested using a standard validation dataset to ensure no unintended change of functionality
- [x] All code adheres to the style guide
- [x] MD5 sums have been updated
- [x] The PR author has addressed all comments

## 🗂️ Associated Documentation (to be completed by Theiagen developer)

- [ ] Relevant documentation on the Public Health Resources "PHB Main" has been updated
- [x] Workflow diagrams have been updated to reflect changes

### CODE REVIEW

**Comment by cimendes** [comment]
@sage-wright I'm setting this as ready to review as I could use the help in testing it!

**Comment by cimendes** [comment]
**Propagation of new input parameters check and validation!**

- **Freyja_FASTQ**
image
https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/91cf4f50-ad60-485d-8f69-7c322770883c

- **TheiaCoV_FASTA**
image
https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/19b328f8-b052-44e4-87bc-ee9f91ad2784

- **TheiaCoV_Illumina_PE**
image
https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/c7e03fbe-a50b-4f96-a9a9-7311b71620f7

- **TheiaCoV_Illumina_SE**
image
https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/1c079d2d-a871-482b-87f7-1f75764482cf

- **TheiaCoV_ONT**
No exposed inputs changed!
https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/78421021-9749-47f8-b269-4303e5700f88 (Some failures expected for, I believe, monkeypox virus)

**Comment by cimendes** [comment]
**Propagation of new input parameters check and validation! (Continued)**

- **TheiaEuk_Illumina_PE**
  - image
  - To be tested

- **TheiaMeta_Illumina_PE**
  - No exposed input parameters altered
  - https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/6ac7a91b-14a1-43a1-a46e-7efc814abe99
  
- **TheiaProk_Illumina_PE**
  - image
  - https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/2f69cd18-6d4d-46d1-a615-163fe9835a6a
  
- **TheiaProk_Illumina_SE**
  -image
  - https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/88e43055-0c27-4b12-a4a5-70b14d0a09ac

**Comment by cimendes** [comment]
> @cimendes when we have *_minlength do you think it makes sense to change that to *_min_length; same for maxlength -> max_length

Ops, sorry I missed this message! It is now done!

**Comment by sage-wright** [comment]
- [ ] TheiaProk PE default params [here](https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Wright_PHBG_Sandbox/job_history/e89cb75a-9983-426f-ab1b-675386fa7b84)
- [ ] TheiaProk SE skip screen otherwise default params [here](https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Wright_PHBG_Sandbox/job_history/ac1e0a0a-42bb-4f4e-bd64-6f7b7257424e)
- [ ] TheiaCoV ONT [here](https://app.terra.bio/#workspaces/cdc-terra-resources/Theiagen_Wright_SC2_Sandbox/job_history/dd9ec0dc-b935-44a8-9c30-17ee477a6e52)
- [ ] TheiaCoV FASTA [here](https://app.terra.bio/#workspaces/cdc-terra-resources/Theiagen_Wright_SC2_Sandbox/job_history/dd9ec0dc-b935-44a8-9c30-17ee477a6e52)

**Review by sage-wright — APPROVED** [review]
Will merge upon successful test completion. Well done, Ines ⭐

**Comment by sage-wright** [comment]
Yay! Good job.

**Pull request merged**
