### PR TITLE
[TheiaCov & TheiaProk & TheiaEuk] read screen ONT bugfix and improvements

### LINKED ISSUE #588: read screen incorrectly counting basepairs
:bug:

### :pencil: Describe the Issue

I came across some ONT data where the (raw) read screen task fails to accurately count # of basepairs with some ONT FASTQ files. This bash one-liner...
https://github.com/theiagen/public_health_bioinformatics/blob/1508bb594272d95e85aa37dfd6bac133d8fd75d5/tasks/quality_control/comparisons/task_screen.wdl#L55

...is failing due to tabs being present in the FASTQ header, example:

```
@95188ab4-78ef-44dd-8c17-67881e09547c   qs:f:3.89145    du:f:4.8936     mx:i:2  ch:i:2  st:Z:2024-08-11T18:05:38.980+00:00      rn:i:-1 fn:Z:FAW95599_9a7a72fa_fad33a0d_70.pod5 sm:f:414.135    sd:f:105.409      sv:Z:pa dx:i:0  RG:Z:fad33a0d89d184b44598c61e6e434edb1ebe861e_dna_r10.4.1_e8.2_400bps_sup@v5.0.0        pi:Z:974f9db2-55ba-4d24-a674-e7a22d5daa1a       sp:i:403278     BC:Z:V23004070
```

For this particular sample, the `raw_read_screen` outputs this and FAILS the sample:

```
"FAIL; the number of basepairs (1043344) is below the minimum of 2241820"
```
When `fastq-scan` shows the true number of basepairs, which is much higher for this 360 MB .fastq.gz file:
```
$ zcat sample01_sup.fastq.gz | fastq-scan -q
{
    "qc_stats": {
        "total_bp": 434069800,
        "coverage": 0.00,
        "read_total": 87764,
        "read_min": 1,
        "read_mean": 4945.88,
        "read_std": 7898.69,
        "read_median": 2086,
        "read_max": 337738,
        "read_25th": 460,
        "read_75th": 5951,
        "qual_min": 2,
        "qual_mean": 28.9399,
        "qual_std": 12.0037,
        "qual_max": 47,
        "qual_median": 33,
        "qual_25th": 19,
        "qual_75th": 39
    }
}
```

### :repeat: How to Reproduce 

Ask me for a link to the theiaprok_ont workflow in Terra where this behavior was observed. Prefer not to post this link publicly to preserve privacy.

Feel free to answer the following questions to help us understand:
- Was the workflow run on the Terra platform? Was it Terra on Azure or GCP? **Terra on GCP**
  - If necessary, we may ask you to share your Terra workspace with us. Usually READER access is sufficient, but we may ask for WRITER access if we need to make changes to the workspace to reproduce the issue. 
- Was the workflow run locally using `miniwdl` or `cromwell`?
  - If so, what was the exact command was used to launch the workflow?

### :computer: Version Information

TheiaProk_ONT v2.1.0

### PR DESCRIPTION
**Pull request by kapsakcj**
~~Will update this later, setting as draft for now~~ Ready for review

This PR closes #588

🗑️ This dev branch should be deleted after merging to main.

## :brain: Summary

This PR updates the 2 WDL tasks `check_reads` and `check_reads_se` that are used in the "read_screen" tasks on raw and cleaned reads throughout most TheiaCov and TheiaProk workflows (all except for FASTA wfs), as well as TheiaEuk_illumina_PE.

For issue #588 , FASTQ files produced by manually basecalling ONT data through Dorado in SUP mode caused this error due to the formatting of the FASTQ headers that include tabs.

This PR updates the lines of code in both tasks to count both:

1. number of basepairs (original error)
2. number of reads in R1 and R2 FASTQs (did not cause an error previously, but prone to errors in the future)

using `fastq-scan` instead of shell/linux commands `paste | cut | tr ` etc. as this is more robust to various FASTQ formats & quirks.

It additionally adds some `DEBUG` statements and updated some shell notation like using `$(command)` instead of legacy '`command`' backtick notation running sub-commands in bash.

I also added `set -euo pipefail` at the top of both tasks to ensure the task exits if any errors/pipefails are encountered.

## :zap: Impacted Workflows/Tasks

- both tasks within `tasks/quality_control/comparisons/task_screen.wdl`
- All theiaprok workflows except FASTA
- All theiacov workflows except FASTA
- TheiaEuk_Illumina_PE

This PR may lead to different results in pre-existing outputs: **No**

This PR uses an element that could cause duplicate runs to have different results: **No**

## :hammer_and_wrench: Changes

see description above

### :gear: Algorithm

same docker image as previously, just using `fastq-scan` instead of shell/linux utilities for counting reads and basepairs within those read files

### ➡️ Inputs

none

### ⬅️ Outputs

None

## :test_tube: Testing

- ✅  TheiaProk_ONT on the 2 Shigella sonnei samples (manually basecalled w Dorado in HAC and SUP mode) that caused the error originally: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-Aug2024/job_history/0eb0528e-2431-4936-b055-51ff10f9e872
- ✅ TheiaProk_ONT - 2 shigella samples, ONT data (older R9 data, I think?): https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-Aug2024/job_history/88301a07-11b8-4359-b510-a1d99e3c45cd
- ✅ TheiaProk_Illumina_PE - 3 bacterial samples w/ FASTQs pulled from SRA: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-Aug2024/job_history/c6389f8d-655e-485c-847e-4c7292cc6fdd
- ✅ TheiaCoV_Illumina_PE - 3 Flu samples w/ FASTQs from ILMN basespace: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-Aug2024/job_history/09ef7501-a35c-4192-bc9d-a9b09bcfdf5b

### Suggested Scenarios for Reviewer to Test

Test any of the various workflows that are impacted. A variety of FASTQ files from various sources would be good to test. Like FASTQ files pulled from Basespace, pulled from SRA and/or ENA, ONT data from ClearLabs, ONT data from usual ONT platforms, anything really.

It would be good to test out oddball FASTQ files that have formatting quirks.

Review the log files for the raw read screen and clean read screen tasks to ensure number of bases & number of reads are counted properly.

## :microscope: Final Developer Checklist

- [x] The workflow/task has been tested and results, including file contents, are as anticipated
- [x] The CI/CD has been adjusted and tests are passing (Theiagen developers)
- [x] Code changes follow the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-51b66a47dde54c798f35d673fff80249)
- [x] Documentation and/or workflow diagrams have been updated if applicable (Theiagen developers only)

## 🎯 Reviewer Checklist

- [ ] All changed results have been confirmed
- [ ] You have tested the PR appropriately (see the [testing guide](https://theiagen.notion.site/PR-Testing-Guide-Determining-Appropriate-Levels-of-Testing-4764e98a6aeb460185039c0896714590) for more information)
- [ ] All code adheres to the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-51b66a47dde54c798f35d673fff80249)
- [ ] MD5 sums have been updated
- [ ] The PR author has addressed all comments
- [ ] The documentation has been updated

### CODE REVIEW

**Comment by sage-wright** [comment]
Oh I'm excited about the DEBUG statements & removing the legacy backticks.

One funny note about fastq-scan -- it also assumes FASTQs have 4 lines 🤷 I'm not sure how sophisticated any of the already established tools are regarding potentially different FASTQ formats lol 😂 
https://github.com/rpetit3/fastq-scan/blob/966991c58bd44cbf7644851b7118f7d06146f3c5/fastq-scan.cpp#L244

**Comment by kapsakcj** [comment]
oh sheesh ok. well it handled these FASTQS better anyways. Probably the `paste` or `tr` that was causing the issue originally...

and I didn't convert all backtick notation throughout the task, just the lines that I was editing. I can go back and swap all those out if you'd like.

One more thing to consider changing...the current docker image includes `fastq-scan` 0.4.4. 

Robert released v1.0.1 https://github.com/rpetit3/fastq-scan/releases/tag/v1.0.1 and mentioned adding support for very large FASTQs. IDK what defines "very large" but if we encounter any super huge FASTQs, we may consider upgrading to this docker image which includes fastq-scan v1.0.1: `quay.io/bactopia/gather_samples:2.2.0` https://quay.io/repository/bactopia/gather_samples?tab=tags

I can update the docker image, but would like to re-run the tests in Terra since idk what else changed between the 2 docker images

**Review by sage-wright — COMMENTED** [review]
Code changes look great. Will merge upon successful completion of test [here](https://app.terra.bio/#workspaces/theiagen-validations/sage_viral/job_history/383fa2c8-dff1-4931-89c5-7064bcda5378) [TheiaCoV ONT]

**Comment by sage-wright** [comment]
I think we're fine with the older version for now? It's definitely something we would want to consider when we encounter a "really huge" fastq

**Comment by sage-wright** [comment]
Looks like the only different with the latest version is using `long int` instead of regular `int` so I guess those FASTQs were REALLY huge https://github.com/rpetit3/fastq-scan/commit/966991c58bd44cbf7644851b7118f7d06146f3c5

**Comment by kapsakcj** [comment]
OK, agreed. The user can always enable `skip_screen` and/or downsample the FASTQ w RASUSA prior to these workflows anyways

**Review by sage-wright — APPROVED** [review]
Tests didn't completely finish, but the read screen tasks did & were successful. Well done.

**Pull request merged**
