### PR TITLE
Update tbp-parser Docker and new output 

### PR DESCRIPTION
**Pull request by sage-wright**
Closes <Issue number>

## :hammer_and_wrench: Changes Being Made

This PR updates the default `tbp-parser` Docker image and introduces a new output -- the average depth.

### Outputs

Float `tbp_parser_average_genome_depth`

## :microscope: Quality checks

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The workflow/task has been tested locally and on Terra
- [x] The CI/CD has been adjusted and tests are passing
- [x] Everything follows the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-bb456f34322d4f4db699d4029050481c)

### CODE REVIEW

**Comment by sage-wright** [comment]
That is not intended

**Comment by cimendes** [comment]
Testing on Terra:
- TheiaProk_Illumina_PE (n=335): https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/91742a2f-7667-4011-ade7-6d0c1110d2eb
- TheiaProk_Illumina_SE (n=100): https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/54a431c2-32e8-4767-b4e9-14d52e0b711e
- TheiaProk_ONT (n=26): https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/f48faaed-e950-459f-9d78-91b675a49288

The code looks good! I will approve once all the test runs pass and the new output column is correctly populated onto the datatable. :)

**Comment by cimendes** [comment]
Found a little issue with this branch where very few samples are failing with the following error message:

`Bad output 'tbp_parser.tbp_parser_average_genome_depth': Failed to read_float("AVG_DEPTH") (reason 1 of 1): For input string: "-nan"`

Job link to an example on Illumina_SE: https://job-manager.dsde-prod.broadinstitute.org/jobs/83f25542-4801-4b15-a3cb-efd0743a591d

Job link to an example on ONT: https://job-manager.dsde-prod.broadinstitute.org/jobs/83f25542-4801-4b15-a3cb-efd0743a591d

The Job links are posted in the comment above this one.

**Comment by cimendes** [comment]
Retesting with the same datasets on:
- Illumina_PE (fixed issue with wrong docker container being used): https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/8f3333c0-bf59-43e9-bcc9-90be311916cc
- Illumina_SE: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/bc8782df-b05d-4528-9b66-fbd916a2f173
- ONT: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/f1c6aaa1-2883-4188-9d72-639a640386e2

**Comment by cimendes** [comment]
Retesting with commit id [01e1db5](https://github.com/theiagen/public_health_bioinformatics/pull/214/commits/01e1db505c56b1d548fdfd0c75a30c29d7602e74):

- Illumina_PE: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/7dbb862e-d040-4303-9ad1-fc0e49c5eea8
- Illumina_SE: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/0956ebe5-38c4-4d7b-a091-ffe164b7b2bc
- ONT: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/7e5d01f7-4495-4e2b-ad7b-8d92e7a3f82e

**Comment by cimendes** [comment]
Successful tests for all workflows:
- ONT: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/7131138a-2909-4214-9e67-a12eb7fedfa2
- Illumina_PE: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/948360fb-6000-41a0-ae02-b94107547a55
- Illumina_SE: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/84f7bafe-b5b4-4c83-bdc6-51290ab02832

Will approve once the CI is happy!

**Review by cimendes — APPROVED** [review]

**Pull request merged**
