### PR TITLE
added 2 QC thresholds to ANI task to reduce false positives 

### PR DESCRIPTION
**Pull request by kapsakcj**
~~FYI: leaving in a draft state until further testing is done and feedback is received. Code changes are pretty much finished.~~
~~We may end up adjusting the default threshold of `92.0` to a different value.~~ adjusted to 80.0

All testing is finished. This PR is ready for review 👀 

#### `tasks/quality_control/task_mummer_ani.wdl` changes

- added new Float input `ani_threshold = 80.0` as per CDC EDLB/PulseNet standard
- added new Float input `percent_bases_aligned_threshold = 70.0` as per CDC EDLB/PulseNet standard
- exposed `cpus` and `memory` Integer optional inputs. 
- added `.txt` suffixes to output files to help differentiate between these and bash variables
- **IMPORTANT CHANGE:** added logic for comparing `ANI_HIGHEST_PERCENTAGE` to `ani_threshold` and only outputting the name of the match if both thresholds are surpassed. If threshold is not surpassed, it will print a message saying `ANI top species match did not surpass the user-defined threshold of ~{ani_threshold}`
- **IMPORTANT CHANGE:** added logic for comparing `ANI_HIGHEST_PERCENT_BASES_ALIGNED` to `percent_bases_aligned_threshold` and only outputting the name of the match if both thresholds are surpassed. If threshold is not surpassed, it will print a message saying `ANI percent bases aligned did not surpass the user-defined threshold of ~{percent_bases_aligned_threshold}`
- added required string output `ani_docker`

#### TheiaProk Illumina PE, SE, ONT, and FASTA workflow changes:

- added new string output `ani_docker` to all workflows
- added `ani_docker` string output to call block for `export_taxon_tables` task

#### `tasks/utilities/task_broad_terra_tools.wdl`/export taxon tables task

- added `ani_docker` string input to this task

## :brain: Context and Rationale

Request from CDPH PulseNet group. 

For example: we do not want to see an Enterobacter cloacae sample show the top ANI hit of `Salmonella_enterica` because that can be confusing to the user. 

Adding this threshold will filter out a large majority, if not ALL false positive top matches where the species is not represented in the database (RGDv2, enteric pathogens) yet ANI & genetic relatedness is high enough to show a result.

### Inputs

new optional inputs: 

- Float `ani_threshold` with default value of `85.00`
- Float `percent_bases_aligned_threshold` with default value of `70.0`
- Int `cpus` with default value of `4`
- Int `memory` with default value of `8`

### Outputs

New required output:

- String `ani_docker`

### Locally

tested locally with miniwdl

### Terra

Successfully ran TheiaProk_Illumina_PE (and export_taxon_tables behaved as expected): https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-theiagen-validations/job_history/af44a279-9918-4d0d-823a-5dccdf65aec0

Tests TODO:

- [x] TheiaProk_ONT: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-theiagen-validations/job_history/ec6ea9ed-7a99-421c-8ad4-4cc17bc77ef4
- [x] TheiaProk_FASTA: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-theiagen-validations/job_history/4f618b50-107e-46fe-b9f2-74ed861f4670
- [x] TheiaProk_Illumina_SE: https://app.terra.bio/#workspaces/theiagen-validations/curtis-sandbox-theiagen-validations/job_history/81e46875-e24f-4a62-8466-3f0343b0c692

## :microscope: Quality checks

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The workflow/task has been tested locally and on Terra
- [x] The CI/CD has been adjusted and tests are passing
- [x] Everything follows the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-bb456f34322d4f4db699d4029050481c)

### CODE REVIEW

**Comment by kapsakcj** [comment]
todos:

- [ ] add new ani_docker output to:
  - [ ] Theiaprok fasta workflow
  - [ ] theiaprok illumina pe workflow
  - [ ] theiaprok illumina se workflow
  - [ ] theiaprok ont workflow 
  - [ ] export_taxon_table task (as well as the call block within workflows)

**Comment by kapsakcj** [comment]
After adding in the 2nd threshold (`percent_bases_aligned_threshold`), all false positives were eliminated in my dataset of ~20 various bacterial species.

Enteric species were output as the `ani_top_species_match` as expected ✅ 

and close relatives (but different genera) had warning messages in the `ani_top_species_match` output String, indicating that one of the 2 thresholds was not met ✅ 

Now to resolve these conflicts 🥲

**Comment by kapsakcj** [comment]
OK, I've rebased this branch to be on top of the most recent `main` branch commits.

Likely will have to adjust CI hashes, but this cleans up the commit history so that all ANI related code changes in this PR occur "now" in the commit history, instead of back when I initially started this dev branch

**Comment by kapsakcj** [comment]
FYI I have merged origin/main into this branch which totally offsets/nullifies the rebasing I did. Should make the "files changed" section much simpler and easier to review code changes

**Comment by kapsakcj** [comment]
Tests ran after the making (hopefully) the final commits:
- [ ] Theiaprok fasta workflow
- [ ] theiaprok illumina pe workflow
- [ ] theiaprok illumina se workflow
- [ ] theiaprok ont workflow

**Review by sage-wright — COMMENTED** [review]
Code looks great. Will approve upon successful tests:

- [x] SE: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Wright_PHBG_Sandbox/job_history/30e07d66-de76-48be-8381-d3cae68453b5
- [x] PE: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Wright_PHBG_Sandbox/job_history/0ebe47d7-e1a1-4648-8206-bf18dcf18bdb
- [ ] FASTA: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Wright_PHBG_Sandbox/job_history/9e543b1d-4be3-4f99-9217-f9f97f2cfd00

**Review by sage-wright — APPROVED** [review]
⭐

**Pull request merged**
