### PR TITLE
add Flu NA Nextclade outputs to theiacov_illumina_pe

### LINKED ISSUE #405: Nextclade Flu NA outputs not populated to Terra data table
:bug:

### :pencil: Describe the Issue

The TheiaCoV_Illumina_PE_PHB workflow runs Nextclade on the NA segment, which provides a clade for this segment, but this output is not populated back to the Terra data table unfortunately. You will have to look into the output files on the step that is specific to running nextclade on the NA segment.

It seems the other outputs are also missing, like the nextclade_tsv File, nextclade_json File, nextclade_qc String, maybe more?

It looks like the aa substitutions and deletions are concatenated with those from the HA segment, so no need to output those separately

### :repeat: How to Reproduce

- Was this run on the Terra platform?
  - Terra on GCP or Azure? **GCP**
- Or were the workflows run locally using `miniwdl` or `cromwell`?
  - **What was the exact command was used to launch the workflow?**
- If possible, we may ask you to share your Terra workspace with us. Usually READER access is sufficient, but we may ask for WRITER access if we need to make changes to the workspace to reproduce the issue.

Example sample `F14049` from the 1-3-0 validation: https://app.terra.bio/#workspaces/theiagen-validations/PHB_Validation_v1-3-0/job_history/9e255e81-77ca-4353-9ce3-9191d3bde5a1

### :fishing_pole_and_fish: Expected Behavior

Output the Nextclade results and files from running nextclade on the NA segment to the Terra data table.

### :floppy_disk: Version Information

v1.3.0 as well as the current state of `main` branch 

1.3.0: https://app.terra.bio/#workspaces/theiagen-validations/PHB_Validation_v1-3-0/job_history/9e255e81-77ca-4353-9ce3-9191d3bde5a1

main: https://app.terra.bio/#workspaces/theiagen-validations/PHB_Validation_nextcladeV3testing/job_history/44abfcc6-90d5-4c91-a4b3-98dff1e0a50e

Look at sample `F14049` for example

### PR DESCRIPTION
**Pull request by kapsakcj**
This PR closes #405 

🗑️ This dev branch should be deleted after merging to main.

## :brain: Aim, Context and Functionality

The TheiaCoV_Illumina_PE_PHB and TheiaCoV_ONT_PHB workflows run Nextclade on the NA segment, which provides a clade for this segment, but this output is not populated back to the Terra data table unfortunately. You will have to look into the output files on the step that is specific to running nextclade on the NA segment. 

Additionally, the output files produced by nextclade (auspice_input_json, nextclade_json, nextclade_tsv) are not populated back to the Terra data table either.

And lastly, the `nextclade_qc` output string is also not populated to the Terra data table.

## :hammer_and_wrench:  Impacted Workflows/Tasks & Changes Being Made
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : **No**

Running this workflow on different occasions could result in different results, e.g. due to use of a live database, "latest" docker image, or stochastic data processing: **No** 

Impacted workflows:

- TheiaCoV_Illumina_PE_PHB
- TheiaCoV_ONT_PHB

I don't believe this impacts TheiaCoV_FASTA_PHB workflow, as the user must provide either `HA` or `NA` for the optional input called `flu_segment`. TheiaCoV_FASTA_PHB is not currently set up to run both HA and NA segments through in parallel. It only runs nextclade once. So I have skipped making these changes to that workflow because that will be a much more involved change that requires extensive dev and testing.

#### 🔄 Data Processing 

Docker/software or software versions changed: **N/A**

Databases or database versions changed: **N/A**

Data processing/commands changed: **N/A**

File processing changed: **N/A**

Compute resources changed: **N/A**

#### ➡️ Inputs 

**N/A**

#### ⬅️ Outputs 

Added 5 new outputs to the TheiaCoV_Illumina_PE_PHB and TheiaCoV_ONT_PHB workflows:

- `String nextclade_json_flu_na = select_first([nextclade_flu_na.nextclade_json, ""])`
- `String auspice_json_flu_na = select_first([nextclade_flu_na.auspice_json, ""])`
- `String nextclade_tsv_flu_na = select_first([nextclade_flu_na.nextclade_tsv, ""])`
- `String nextclade_clade_flu_na = select_first([nextclade_output_parser_flu_na.nextclade_clade, ""])`
- `String? nextclade_qc_flu_na = nextclade_output_parser_flu_na.nextclade_qc`

#### Test Dataset

I used the validation sets for ILMN PE and ONT workflows. I added 2 new H1N1 ONT datasets since the 5 we have currently available are not the best.

#### Commandline Testing with MiniWDL or Cromwell (optional)

Skipped testing locally except for TheiaCoV_ONT, which was successful (log not shown)

#### Terra Testing

See below comments for links and screenshots

#### Suggested Scenarios for Reviewer to Test

Test the 2 impacted workflows with Flu samples

#### Theiagen Version Release Testing (optional)

- Will changes require functional or validation testing (checking outputs etc) during the release? **validation**
- Do new samples need to be added to validation datasets? If so, upload these to the appropriate validation workspace Google bucket (). Please describe the new samples here and why these have been chosen. **I used 2 H1N1 ONT samples from this publication: https://link.springer.com/article/10.1186/s12879-020-05367-y . They have been added to the correct bucket and Terra data table TSV is shared via slack. We can update the PHB_Validation_TEMPLATE workspace data table during validation efforts**
- Are there any output files that should be checked after running the version release testing? **nextclade output TSV, nextclade output JSON, and auspice_input_json**

## :microscope: Final Developer Checklist

- [x] The workflow/task has been tested locally and results, including file contents, are as anticipated
- [x] The workflow/task has been tested on Terra and results, including file contents, are as anticipated
- [x] The CI/CD has been adjusted and tests are passing (to be completed by Theiagen developer)
- [x] Code changes follow the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-bb456f34322d4f4db699d4029050481c)

## 🎯 Reviewer Checklist 

- [ ] All impacted workflows/tasks have been tested on Terra with a different dataset than used for development
- [ ] All reviewer-suggested scenarios have been tested and any additional
- [ ] All changed results have been confirmed to be accurate
- [ ] All workflows/tasks impacted by change/s have been tested using a standard validation dataset to ensure no unintended change of functionality
- [ ] All code adheres to the style guide
- [ ] MD5 sums have been updated
- [ ] The PR author has addressed all comments

## 🗂️ Associated Documentation (to be completed by Theiagen developer)

- [ ] Relevant documentation on the Public Health Resources "PHB Main" has been updated
- [x] Workflow diagrams have been updated to reflect changes

### CODE REVIEW

**Comment by kapsakcj** [comment]
New outputs are populated properly for TheiaCoV_Illumina_PE with Flu:
image

Successful test that produced these outputs is here: https://app.terra.bio/#workspaces/theiagen-validations/PHB_Validation_nextcladeV3testing/job_history/8fd7b653-eaf1-4bb0-86f6-9f5191e343fe

TODO: look at TheiaCoV_ONT test and see what is going on there. 2 outright failures (likely caused by low quality input data?) and the 3 that succeeded look like the quality of the assemblies was not high enough to pass nextclade's default QC parameters. Here's one example:

`In sequence #0 'ERR6359498_A_NA_N1': When processing sequence #0 'ERR6359498_A_NA_N1': When calculating seed matches: Unable to align: seed alignment covers 3.88% of the query sequence, which is less than expected 10.00% (configurable using 'min seed cover' CLI flag or dataset property). This is likely due to low quality of the provided sequence, or due to using incorrect reference sequence.. Note that this sequence will not be included in the results.`

**Comment by kapsakcj** [comment]
Hoping these 2 ONT Flu samples will succeed (they did at the commandline w miniwdl), just had to fix the optional inputs (mainly the "organism" input):

https://app.terra.bio/#workspaces/theiagen-validations/PHB_Validation_nextcladeV3testing/job_history/df910abc-1502-46b8-973a-30e59062dfd6

🤞

**Comment by kapsakcj** [comment]
Here's the new outputs for TheiaCoV_ONT. The 2 new H1N1 samples seem to be of higher quality and thus resulting assemblies were better, and ran more smoothly through nextclade compared to our pre-existing validation datasets for ONT Flu samples:

image

**Comment by cimendes** [comment]
Looks amazing @kapsakcj!!! 🌟 
I visually inspected the code changes and the outputs of your tests, and everything looks amazing!

**Review by cimendes — APPROVED** [review]

**Pull request merged**
