### PR TITLE
Augur_PHB: Set sample_metadata_tsvs input to optional

### LINKED ISSUE #458: [Augur] Set sample_metadata_tsvs input in Augur_PHB to optional
:cool:

### :pushpin: Explain the Request

Change the Augur_PHB input `sample_metadata_tsvs` from required to optional.

### :books: Context

Augur_PHB has an optional feature that allows users to output only a distance tree, which does not use any metadata. However, the sample_metadata_tsvs are still required inputs to the workflow, even if the users are only building a distance tree. This is a hinderance to users that just want a quick tree, without having to go through the time-consuming process of compiling metadata in the right format and running Augur_Prep_PHB.

### :chart_with_upwards_trend: Desired Behavior

The Augur_PHB input `sample_metadata_tsvs` is set to optional. This should not result in any functional changes to the workflow.

### PR DESCRIPTION
**Pull request by jrotieno**
This PR closes #458.

🗑️ This dev branch should <NOT> be deleted after merging to main.

## :brain: Aim, Context and Functionality

This PR features updates to the Augur_Prep_PHB and Augur_PHB workflows enabling a user to run these workflows with only the sequence information and not requiring associated metadata. The use case is such as when a user needs to only generate a distance tree in the newick format.

At present, in addition to sequence data, one can only run Augur_Prep_PHB when continent, country, state and collection date information is available. After this update, only the sequence information will be required.

For Augur_PHB workflow, in addition to assemblies and build name, associated metadata is a requirement. With this update, only the assemblies and build name will be required.

## :hammer_and_wrench:  Impacted Workflows/Tasks & Changes Being Made
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : No, the user will obtain the same results if they saved the required inputs that will be optional.

Running this workflow on different occasions could result in different results, e.g. due to use of a live database, "latest" docker image, or stochastic data processing : No 

#### 🔄 Data Processing 

Docker/software or software versions changed:  No

Databases or database versions changed: No

Data processing/commands changed: Yes, made some inputs optional

File processing changed: No

Compute resources changed: No

#### ➡️ Inputs 

For `Augur_Prep_PHB`, the following inputs have been made optional:
```
collection_date
country
state
continent
```

For `Augur_PHB`, the following inputs have been made optional:
`sample_metadata_tsvs`

#### Terra Testing

The following Tests were done with flu H1N1:
`Augur_Prep_PHB` with the above mentioned inputs as required: https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Otieno_Sandbox/job_history/82bffbed-ca40-4023-870e-78802528a56f

`Augur_Prep_PHB` with the above mentioned inputs not included: https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Otieno_Sandbox/job_history/f630f152-89d9-4fbf-b977-c28303a165da

`Augur_PHB` with metadata: https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Otieno_Sandbox/job_history/88d1aefa-8a4c-4283-b978-bb0d21e7e119

`Augur_PHB` without metadata (but available from prep): https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Otieno_Sandbox/job_history/bf835e21-1292-4fe3-a0f1-4e2f9f54ea45

`Augur_PHB` without metadata (also none from prep): https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Otieno_Sandbox/job_history/b672ec5f-09c4-451d-88e7-a088c889c3d5

The distance trees in all scenarios were the same, with auspice tree only output when metadata is provided.

#### Suggested Scenarios for Reviewer to Test

Test with non-flu pathogens.

## :microscope: Final Developer Checklist

- [ ] The workflow/task has been tested locally and results, including file contents, are as anticipated
- [X] The workflow/task has been tested on Terra and results, including file contents, are as anticipated
- [x] The CI/CD has been adjusted and tests are passing (to be completed by Theiagen developer)
- [X] Code changes follow the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-bb456f34322d4f4db699d4029050481c)

## 🎯 Reviewer Checklist 

- [ ] All impacted workflows/tasks have been tested on Terra with a different dataset than used for development
- [ ] All reviewer-suggested scenarios have been tested and any additional
- [ ] All changed results have been confirmed to be accurate
- [ ] All workflows/tasks impacted by change/s have been tested using a standard validation dataset to ensure no unintended change of functionality
- [ ] All code adheres to the style guide
- [ ] MD5 sums have been updated
- [ ] The PR author has addressed all comments

## 🗂️ Associated Documentation (to be completed by Theiagen developer)

- [x] Relevant documentation on the Public Health Resources "PHB Main" has been updated
- [ ] Workflow diagrams have been updated to reflect changes

### CODE REVIEW

**Review by AndrewLangvt — COMMENTED** [review]
Looks great. At some point, we should look to standardize our usage of ' vs " in our command blocks. That said, both are functional and do not impact the functionality enabled in this PR. 

@emily-smith1 once you complete testing, this can be merged.

**Comment by jrotieno** [comment]
I agree @AndrewLangvt 

@emily-smith1, if testing a pathogen that is not in the TheiaCoV list and running into issues, you may check some notes I made here #509

**Comment by emily-smith1** [comment]
Tested successfully on a concatenated fasta file containing 420 influenza PB2 gene segments [here](https://app.terra.bio/#workspaces/cdph-terrabio-taborda-manual/CDPH_Smith_Sandbox/job_history/a6b4c56e-1d81-4e16-a0d1-69ad4783ffdf). We should add a note to our documentation that the user will need to udpate the min_num_unambig input setting if running this on taxa where we don't have organism tracks.

**Comment by AndrewLangvt** [comment]
@jrotieno can you make the doc update specified by @emily-smith1? Please LMK and I'll approve & merge this to `main`

**Comment by jrotieno** [comment]
@AndrewLangvt, you can go ahead and merge as I have updated the docs with the required inputs when working with non-TheiaCoV pathogens. I am meeting @cimendes tomorrow to rubber duck some additional Augur doc updates.

**Review by AndrewLangvt — APPROVED** [review]

**Pull request merged**
