### PR TITLE
Add emm-typing-tool and hicap tasks

### PR DESCRIPTION
**Pull request by jrotieno**
This PR adds the following tasks

- [x] task for [emmtypingtool](https://github.com/ukhsa-collaboration/emm-typing-tool)
- [x] task for [hicap](https://github.com/scwatts/hicap)

#### emmtyping tool
This tool assigns emm type and subtype by querying the CDC M-type specific database (ftp://ftp.cdc.gov/pub/infectious_diseases/biotech/tsemm/). The task outputs are 1. emm type (and subtype), 2. tool version, and 3. complete tool output file

#### hicap
This tool identifies the cap locus serotype and structure in an _H. influenzae_ assembly. The task outputs are 1. cap genes identified, 2. predicted serotype, 3. tool version, and 4. complete tool output file

### **Test data**
emm-typing tool: _S. pyogenes_ [ERR1733707](https://www.ebi.ac.uk/ena/browser/view/ERR1733707)
hicap: _H. influenzae_ [ERR2560747](https://www.ebi.ac.uk/ena/browser/view/ERR2560747)
inadequate reads, just to see if everything else works as expected: _H. influenzae_ [ERR9850120](https://www.ebi.ac.uk/ena/browser/view/ERR9850120)

[The test run on Terra.bio](https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Otieno_Sandbox/job_history/b02a0ed5-8f25-436c-a79d-9c729f1a3934)

### CODE REVIEW

**Comment by cimendes** [comment]
Tested **emm-typing-tool** and **hicap** in 10 _S. pyogenes_ and 10 _H. influenzae_ genomes: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/62e0c256-a417-4c0d-b711-a43e009836ac

All samples ran successfully, with the expected outputs being produced for each set of genomes. 
image
image

The sub-workflows identified all 20 species correctly, with no overlapping output being produced. 

### Suggestions
- To harmonize the name of the output tables better with the rest of the species typing tools (e.g. staphopiasccmec_results_tsv), I suggest renaming the output file columns to **emmtypingtool_results_xml** and **hicap_results_tsv**. 
- Having **emmtypingtool_results** and **emmtypingtool_results_tsv** might be a bit confusing so I suggest renaming the first column to **emmtypingtool_emm_type**
- the dockerfile used is not outputted for any of the two tools, but it's an output of many other tools. Is this something that should be standard? If so, it should be implemented before merging. (e.g. staphopiasccmec has as output the dockerfile, srst2_vivrio doesn't) 
- For both tasks, the cpus can be overwritten but the memory cannot. I would add it as an optional input. 
- The output files of hicap are named `~{samplename}.hicap.tsv` whereas for emm-typing-tool they are just named `~{samplename}.xml`. I would adjust the name of the latter so it's more self descriptive like hicap (e.g. `~{samplename}.emmtypingtool.xml`)

**Comment by cimendes** [comment]
Tested emm-typing-tool and hicap for TheiaProk_Illumina_PE with commit id [7b5e98e](https://github.com/theiagen/public_health_bioinformatics/pull/63/commits/7b5e98e78667a37014a4f7120e8d717ed4db8fb6) in 10 _S. pyogenes_ and 10 _H. influenzae_ genomes: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/af5b2644-538e-41c6-9d0c-481f63d9449f

image
image

Once again, the sub-workflows identified all 20 species correctly, with no overlapping output being produced.
The new output columns have been produced correctly

Thanks, @jrotieno for implementing all of my suggestions! The output columns on Terra data table are much more intuitive now. I did notice that the docker containers for  emm-typing-tool and hicap are not exposed in the input table. I think they need to be exposed directly in merlin_magic, but @kapsakcj can confirm this. 

image

My last suggestion is to expose to the user these containers so that they can be altered by the user.

**Comment by kapsakcj** [comment]
>I did notice that the docker containers for emm-typing-tool and hicap are not exposed in the input table. I think they need to be exposed directly in merlin_magic, but @kapsakcj can confirm this.

Yes, you are correct, the optional docker image inputs must be added to the merlin_magic subwf in order for the user to alter these inputs for the TheiaProk_Illumina_PE workflow

**Comment by jrotieno** [comment]
Docker containers for emm-typing-tool and hicap now exposed in the Terra.bio input table. Thanks @cimendes and @kapsakcj

**Comment by cimendes** [comment]
Successful run with commit [7b5e98e](https://github.com/theiagen/public_health_bioinformatics/pull/63/commits/7b5e98e78667a37014a4f7120e8d717ed4db8fb6)
https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/cbb999ae-b79d-40ca-b552-7daeb1535432

Could confirm that the docker images for hicap and emmtypingtool are now exposed to the user to be overwritten: 
image

**Comment by cimendes** [comment]
Nicely done! LGTM! 😄

**Review by cimendes — APPROVED** [review]
Don't forget to update the documentation! ;)

**Review by cimendes — APPROVED** [review]
Documentation has been updated, including lucidchart: https://www.notion.so/theiagen/TheiaProk-Workflow-Series-01d197bf80e542aabd943a3e95f6097e

**Pull request merged**
