### PR TITLE
update default nextclade dataset tag to "2023-09-21T12:00:00Z" for all TheiaCov wfs

### PR DESCRIPTION
**Pull request by kapsakcj**
applied on wfs: theiacov clearlabs, fasta, ilmn pe, ilmn se, ont

## :hammer_and_wrench: Changes Being Made

Updates default `nextclade_dataset_tag` for sars-cov-2 to be up to date (as of 2023-10-10) across 5 TheiaCov workflows

## :brain: Context and Rationale

Staying up-to-date. Specific to sars-cov-2 (as is many of the default inputs for TheiaCov workflows)

### Inputs

N/A

### Outputs

N/A

### Locally

Did not test locally, will test all workflows in Terra

## :microscope: Quality checks

Pull Request (PR) checklist:
- [x] Include a description of what is in this pull request in this message.
- [x] The workflow/task has been tested locally and on Terra
- [x] The CI/CD has been adjusted and tests are passing
- [x] Everything follows the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-bb456f34322d4f4db699d4029050481c)

### CODE REVIEW

**Comment by kapsakcj** [comment]
branch has been rebased, will update CI momentarily

**Comment by kapsakcj** [comment]
Tests to run prior to marking ready for review:

- [ ] Theiacov_fasta
- [ ] theiacov_illumina_pe
- [ ] theiacov_illumina_se
- [ ] theiacov_ont
- [ ] theiacov_clearlabs

**Review by sage-wright — APPROVED** [review]

**Review by sage-wright — APPROVED** [review]

**Comment by kapsakcj** [comment]
? what is happening with these stale reviews. I didn't dismiss anything!

I have never seen this before

**Review by sage-wright — APPROVED** [review]

**Review by sage-wright — DISMISSED** [review]

**Review by michellescribner — DISMISSED** [review]
Merging on behalf of Sage

**Review by kevinlibuit — DISMISSED** [review]

**Review by kevinlibuit — APPROVED** [review]

**Pull request merged**
