### PR TITLE
[NCBI Scrub Standalone Workflows] Correct output declarations for the number of spots removed

### LINKED ISSUE #609: [NCBI-Scrub Standalone] Bug when importing latest version due to undeclared values
:bug:

### :pencil: Describe the Issue

image
Happened when importing/updating to version v2.2.0

Most likely an unintended consequence of #202

### PR DESCRIPTION
**Pull request by cimendes**
This PR closes #609 

🗑️ This dev branch should NOT be deleted after merging to main.

## :brain: Summary

This very small PR fixed the output declaration on two workflows:
- NCBI_Scrub_SE_PHB
- NCBI_Scrub_PE_PHB

This is due to a bug introduced possibly in #527. The ncbi-scrub (or HRRT) task was updated to the latest version (v2.2.1), but changes were only propagated to the TheiaCoV workflows. 

This PR closes the circle by updating these two workflows to allow the utilization of this tool independently. 

## :zap: Impacted Workflows/Tasks

Only the workflows mentioned above are impacted. 

This PR may lead to different results in pre-existing outputs: **No**

This PR uses an element that could cause duplicate runs to have different results: **No**

### PE Workflow

     Int read1_human_spots_removed = ncbi_scrub_pe.read1_human_spots_removed
     Int read2_human_spots_removed = ncbi_scrub_pe.read2_human_spots_removed

are now condensed into a singular output

     Int ncbi_scrub_human_spots_removed = ncbi_scrub_pe.human_spots_removed

### SE Workflow

    Int human_spots_removed = ncbi_scrub_se.read1_human_spots_removed

is now 

    Int ncbi_scrub_human_spots_removed = ncbi_scrub_se.human_spots_removed

### :gear: Algorithm

No changes were made.

### ➡️ Inputs

No input changes were made.

### ⬅️ Outputs

Outputs have been updated for the NCBI_Scrub_SE and NCBI_Scrub_PE workflows as stated above. 

#### PE
- Successfully imported the workflow
  - image
- Test run: https://app.terra.bio/#workspaces/theiagen-validations/ines_sandbox/job_history/8e9ff7aa-bc5d-49f7-b36f-73fba2494a82

#### SE
- Successfully imported the workflow
  - image
- Test run: https://app.terra.bio/#workspaces/theiagen-validations/ines_sandbox/job_history/6c31c08f-3968-4101-a4b5-8154864ca326

## :microscope: Final Developer Checklist

- [x] The workflow/task has been tested and results, including file contents, are as anticipated
- [x] The CI/CD has been adjusted and tests are passing (Theiagen developers)
- [x] Code changes follow the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-51b66a47dde54c798f35d673fff80249)
- [x] Documentation and/or workflow diagrams have been updated if applicable (Theiagen developers only)

## 🎯 Reviewer Checklist

- [x] All changed results have been confirmed
- [x] You have tested the PR appropriately (see the [testing guide](https://theiagen.notion.site/PR-Testing-Guide-Determining-Appropriate-Levels-of-Testing-4764e98a6aeb460185039c0896714590) for more information)
- [x] All code adheres to the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-51b66a47dde54c798f35d673fff80249)
- [x] MD5 sums have been updated
- [x] The PR author has addressed all comments
- [x] The documentation has been updated

### CODE REVIEW

**Comment by cimendes** [comment]
Waiting on documentation PR to be merged

**Comment by jrotieno** [comment]
Tested these on some WNV samples.
NCBI_Scrub_PE_PHB: https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Otieno_Sandbox/job_history/97c8eced-ae61-436d-a588-8500266ecc18

NCBI_Scrub_SE_PHB: https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Otieno_Sandbox/job_history/55d7c5cc-deb3-4efb-9a70-02f2594de289

While not affected, just running TheiaCoV_Illumina_PE_PHB here: https://app.terra.bio/#workspaces/theiagen-training-workspaces/Theiagen_Otieno_Sandbox/job_history/af68e400-e719-4817-8840-597c816e6522

**Comment by jrotieno** [comment]
@cimendes all tests passed. Well done!

**Comment by cimendes** [comment]
@sage-wright @jrotieno documentation has now been updated

**Review by sage-wright — APPROVED** [review]
excellent!

**Pull request merged**
