### PR TITLE
[TheiaCoV] Add GenoFLU for flu whole-genome genotyping

### LINKED ISSUE #537: Add Flu Genotype
:cool:

### :pushpin: Explain the Request

Call flu genotype using all segments

### PR DESCRIPTION
**Pull request by sage-wright**
This PR closes #537.

🗑️ This dev branch should be deleted after merging to main.

## :brain: Aim, Context and Functionality

This PR adds GenoFLU, a tool made by USDA, which will determine the whole-genome genotype of the sample

## :hammer_and_wrench:  Impacted Workflows/Tasks & Changes Being Made
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : Yes/No

Running this workflow on different occasions could result in different results, e.g. due to use of a live database, "latest" docker image, or stochastic data processing : Yes/No 

New task added GenoFLU to the flu_track

#### 🔄 Data Processing 

Docker/software or software versions changed: 

GenoFLU v1.03 added

Databases or database versions changed:

Data processing/commands changed:

File processing changed:

Compute resources changed:

#### ➡️ Inputs 

New (appear in terra under `flu_track`):
- `File? genoflu_cross_reference`
- `Int genoflu_cpu`
- `Int genoflu_disk_size`
- `String genoflu_docker`
- `Int genoflu_memory`

#### ⬅️ Outputs 

New (theiacov_illumina_pe & _ont):
- `String genoflu_version`
- `String genoflu_genotype`
- `String genoflu_all_segments`
- `File genoflu_output_tsv`

#### Terra Testing

- testing on 96 PE samples [here](https://app.terra.bio/#workspaces/theiagen-validations/sage_viral/job_history/332e346d-a47b-4b9c-9732-a59a5f7af0fa)
- testing on 25 more diverse samples [here](https://app.terra.bio/#workspaces/theiagen-validations/sage_viral/job_history/0a59e3dd-4c3c-4c97-987b-da4b386832f8)
- ONT test [here](https://app.terra.bio/#workspaces/theiagen-validations/sage_viral/job_history/f7e05790-5fce-41f9-ab2b-2f9256526e49)

## :microscope: Final Developer Checklist

- [x] The workflow/task has been tested locally and results, including file contents, are as anticipated
- [x] The workflow/task has been tested on Terra and results, including file contents, are as anticipated
- [x] The CI/CD has been adjusted and tests are passing (to be completed by Theiagen developer)
- [x] Code changes follow the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-bb456f34322d4f4db699d4029050481c)

## 🎯 Reviewer Checklist 

- [ ] All impacted workflows/tasks have been tested on Terra with a different dataset than used for development
- [ ] All reviewer-suggested scenarios have been tested and any additional
- [ ] All changed results have been confirmed to be accurate
- [ ] All workflows/tasks impacted by change/s have been tested using a standard validation dataset to ensure no unintended change of functionality
- [ ] All code adheres to the style guide
- [ ] MD5 sums have been updated
- [ ] The PR author has addressed all comments

## 🗂️ Associated Documentation (to be completed by Theiagen developer)

- [ ] Relevant documentation on the Public Health Resources "PHB Main" has been updated
- [ ] Workflow diagrams have been updated to reflect changes

### CODE REVIEW

**Comment by jrotieno** [comment]
Lovely work @sage-wright. A few thoughts;
1. Should we also have this implemented for TheiaCoV_FASTA_PHB?
2. It appears that GenoFLU currently characterizes only H5N1? If that is the case, maybe we want to have it only run when subtype is H5N1?

**Comment by sage-wright** [comment]
1. We can implement this for TheiaCoV_FASTA_PHB! I forgot about that workflow
2. I thought [this is the list of relevant genotypes that GenoFLU can characterize](https://github.com/USDA-VS/GenoFLU/blob/main/dependencies/genotype_key.xlsx); could I be mistaken and misinterpreting this?

**Comment by sage-wright** [comment]
[FASTA}(https://app.terra.bio/#workspaces/theiagen-validations/sage_viral/job_history/4c851eab-5ad6-401b-8b24-7b4105c9b3c0) tested here;
retest of [Illumina_PE](https://app.terra.bio/#workspaces/theiagen-validations/sage_viral/job_history/b59d6a28-bc44-499b-ab66-9b9a07bbc566) here, which should only output the genoflu stuff for H5N1

**Review by jrotieno — APPROVED** [review]
Thanks for the quick turnaround and testing!

**Pull request merged**
