### PR TITLE
[Mercury] bump mercury docker to 1.0.9: bugfix for GISAID metadata covv_coverage column

### LINKED ISSUE #612: [Mercury] silent OOM error with download_terra_table task
:bug:

### :pencil: Describe the Issue

A user ran into repeated errors when running the Mercury_prep_N_Batch workflow v2.2.0, specifically the download_terra_table task. The task stalled while running the `export_large_tsv.py` script, leading to long runtimes and a not very clear error message. Error messages:

From job manager: `Task mercury_prep_n_batch.download_terra_table:NA:1 failed. The job was stopped before the command finished. PAPI error code 10. The assigned worker has failed to complete the operation`

The task ran for 38 minutes before failing.

end of the log file:
```
25882 miseq_specimen(s) to export.
Getting all 26 pages of entity data.
0%| | 0/26 [00:00<?, ?it/s] 4%|▍ | 1/26 [00:01<00:43, 1.74s/it] 8%|▊ | 2/26 [00:03<00:45, 1.89s/it] 12%|█▏ | 3/26 [00:05<00:46, 2.00s/it] 15%|█▌ | 4/26 [00:08<00:45, 2.08s/it] 19%|█▉ | 5/26 [00:10<00:45, 2.19s/it] 23%|██▎ | 6/26 [00:12<00:44, 2.24s/it] 27%|██▋ | 7/26 [00:15<00:44, 2.33s/it] 31%|███ | 8/26 [00:17<00:42, 2.37s/it] 35%|███▍ | 9/26 [00:20<00:42, 2.48s/it] 38%|███▊ | 10/26 [00:22<00:39, 2.48s/it] 42%|████▏ | 11/26 [00:25<00:37, 2.48s/it] 46%|████▌ | 12/26 [00:28<00:35, 2.52s/it] 50%|█████ | 13/26 [00:31<00:35, 2.69s/it] 54%|█████▍ | 14/26 [00:33<00:31, 2.66s/it]
```

With no indication of a OOM error like the usual `Killed` message we see. I don't think this script can properly handle OOM errors.

When I ran the task locally on my devVM, it completed without issue, likely due to the larger amount of memory that was made available from running locally.

When I re-launched the task in Terra with `memory` set to `4`, the task ran successfully.

**I recommend that we set the default value for `memory` for this task to at a minimum 2, but 4 if we want to be sure. When I observed RAM consumption when running locally, it did not seem to consume more than ~1.4GB of RAM, but that was just from watching `htop` and could be inaccurate. Line of code is here: https://github.com/theiagen/public_health_bioinformatics/blob/5be343354f716d77e9e4a0fb4a2ec10eb3bc00a5/tasks/utilities/data_export/task_download_terra_table.wdl#L15**

### :repeat: How to Reproduce 

To reproduce, try to run the Mercury_prep_N_batch workflow on a data table that has a large number of samples, for example >20,000 samples. I can provide this user's workspace and data table upon request.

Feel free to answer the following questions to help us understand:
- Was the workflow run on the Terra platform? Was it Terra on Azure or GCP?
  - If necessary, we may ask you to share your Terra workspace with us. Usually READER access is sufficient, but we may ask for WRITER access if we need to make changes to the workspace to reproduce the issue. 
- Was the workflow run locally using `miniwdl` or `cromwell`?
  - If so, what was the exact command was used to launch the workflow?
-->

### :computer: Version Information

v2.2.0

### LINKED ISSUE #657: Mercury: incorrect column used when `using_clearlabs_data` is `true`
:bug:

### :pencil: Describe the Issue

Described on an issue over in the Mercury repo, as the code there needs to be changed (I think, someone please double check our logic): https://github.com/theiagen/mercury/issues/4

### :repeat: How to Reproduce 

Since at least Mercury/PHB v2.0.1 (if not prior versions) and up to the current v2.2.1 version, the wrong column may have been used for setting the `Coverage` column for GISAID and NCBI metadata TSVs for submission produced by Mercury. 

This can be reproduced with any dataset and Mercury v2.2.1

Feel free to answer the following questions to help us understand:
- Was the workflow run on the Terra platform? Was it Terra on Azure or GCP? GCP
  - If necessary, we may ask you to share your Terra workspace with us. Usually READER access is sufficient, but we may ask for WRITER access if we need to make changes to the workspace to reproduce the issue. 
- Was the workflow run locally using `miniwdl` or `cromwell`?
  - If so, what was the exact command was used to launch the workflow?
-->

### PR DESCRIPTION
**Pull request by kapsakcj**
This PR closes #657 and closes #612

🗑️ This dev branch should NOT be deleted after merging to main. We have 1 lab that may be actively using this branch

## :brain: Summary

v1.0.9 of Mercury uses the correct column `clearlabs_sequencing_depth` when preparing CL GISAID metadata TSV file.

v1.0.9 also adds functionality to check if FASTQ files already exist in the destination google bucket (usually `gs://theiagen_sra_transfer`) prior to copying the file there. If the file exists, it will skip the copy, and if the file is not found, it will copy the file there.

Also updated the `download_terra_table` task to have 2 GB RAM by default instead of 1, added `set -euopipefail`, ensured preemptible is off, and enabled memory retry feature.

## :zap: Impacted Workflows/Tasks

- Mercury task & Mercury_Prep_N_Batch workflow
- Workflows that use the `download_terra_table` task:
  - CZGenEPI_Prep

This PR may lead to different results in pre-existing outputs: **Yes**

This PR uses an element that could cause duplicate runs to have different results: **No**

## :hammer_and_wrench: Changes

See Mercury release & changelog here for discrete Mercury python code changes: https://github.com/theiagen/mercury/releases/tag/v1.0.9

### ➡️ Inputs

No

### ⬅️ Outputs

Yes, the GISAID metadata TSV produced by Mercury will have the correct values in the `covv_coverage` column

## :test_tube: Testing

✅ Successful test here: https://app.terra.bio/#workspaces/cdph-terrabio-taborda-manual/CDPH_Support_Sandbox/job_history/98caeb2e-d149-49ad-bd17-f54ff60dc09e
- In this test, 1 FASTQ file was already present on the destination bucket, so Mercury did not attempt to transfer it (expected behavior). 
- For the remaining 31 samples, their FASTQ files were not present on the destination bucket so Mercury did transfer them. (FYI I deleted the files off the bucket for privacy reasons, but the logs show that it happened successfully)
- Also, the output GISAID metadata TSV does have the correct values in the `covv_coverage` column from the Terra column `clearlabs_sequencing_depth`

### Suggested Scenarios for Reviewer to Test

Test Mercury_Prep_N_Batch workflow with clear labs data (or Illumina) and ensure that `skip_ncbi` is set to `false` to test the copying of FASTQ files.

## :microscope: Final Developer Checklist

- [x] The workflow/task has been tested and results, including file contents, are as anticipated
- [x] The CI/CD has been adjusted and tests are passing (Theiagen developers)
- [x] Code changes follow the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-51b66a47dde54c798f35d673fff80249)
- [x] Documentation and/or workflow diagrams have been updated if applicable (Theiagen developers only)

## 🎯 Reviewer Checklist

- [x] All changed results have been confirmed
- [x] You have tested the PR appropriately (see the [testing guide](https://theiagen.notion.site/PR-Testing-Guide-Determining-Appropriate-Levels-of-Testing-4764e98a6aeb460185039c0896714590) for more information)
- [x] All code adheres to the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-51b66a47dde54c798f35d673fff80249)
- [x] MD5 sums have been updated
- [x] The PR author has addressed all comments
- [x] The documentation has been updated

### CODE REVIEW

**Comment by kapsakcj** [comment]
Another test, particularly for the `download_terra_table` task change to use 2GB of memory instead of 1. This workflow shows success for that task on the first try, whereas it failed previously due to the >26k samples in the data table downloaded in the workflow. The workflow failed later in the `mercury` task, but I expected that to occur (purposely set optional inputs incorrectly) https://app.terra.bio/#workspaces/cdph-terrabio-taborda-manual/CDPH_Support_Sandbox/job_history/0ff76026-711f-439d-ba71-4eefeb364919

Specific for Issue #612

**Comment by sage-wright** [comment]
do we have any documentation that needs to be updated here? thinking about the mercury page's default docker maybe?

**Comment by kapsakcj** [comment]
> do we have any documentation that needs to be updated here? thinking about the mercury page's default docker maybe?

I just fixed 2 spots in the docs that I missed previously, thanks for asking.

I'm not sure if there are other places to update. My searches through the code do not show anything else.

**Comment by kapsakcj** [comment]
Please keep the dev branch available until we get closer to doing a version release. there is 1 lab that is actively using this branch.

I will share some of their successful workflows in slack in case you'd like to review

**Review by sage-wright — APPROVED** [review]
⭐

**Pull request merged**
