### PR TITLE
TheiaValidate: Compare file contents (#264)

### PR DESCRIPTION
**Pull request by sage-wright**
This PR closes the loop on the adding file comparisons to TheiaValidate

🗑️ This dev branch should be deleted after merging to main.

## :brain: Aim, Context and Functionality

This PR pushes the changes into main that have been thoroughly tested as part of #264

## :hammer_and_wrench:  Impacted Workflows/Tasks & Changes Being Made
This will affect the behavior of the workflow(s) even if users don’t change any workflow inputs relative to the last version : No

Running this workflow on different occasions could result in different results, e.g. due to use of a live database, "latest" docker image, or stochastic data processing : No 

#### 🔄 Data Processing 

Docker/software or software versions changed: 

TheiaValidate updated to now compare files

Databases or database versions changed:

Data processing/commands changed:

File processing changed:

Compute resources changed:

#### ⬅️ Outputs 

File comparison outputs now created

## :microscope: Final Developer Checklist

- [x] The workflow/task has been tested locally and results, including file contents, are as anticipated
- [x] The workflow/task has been tested on Terra and results, including file contents, are as anticipated
- [x] The CI/CD has been adjusted and tests are passing (to be completed by Theiagen developer)
- [x] Code changes follow the [style guide](https://theiagen.notion.site/Style-Guide-WDL-Workflow-Development-bb456f34322d4f4db699d4029050481c)

## 🎯 Reviewer Checklist 

- [x] All impacted workflows/tasks have been tested on Terra with a different dataset than used for development
- [x] All reviewer-suggested scenarios have been tested and any additional
- [x] All changed results have been confirmed to be accurate
- [x] All workflows/tasks impacted by change/s have been tested using a standard validation dataset to ensure no unintended change of functionality
- [x] All code adheres to the style guide
- [x] MD5 sums have been updated
- [x] The PR author has addressed all comments

## 🗂️ Associated Documentation (to be completed by Theiagen developer)

- [x] Relevant documentation on the Public Health Resources "PHB Main" has been updated
- [x] Workflow diagrams have been updated to reflect changes

### CODE REVIEW

**Comment by cimendes** [comment]
Optional inputs present as expected:
image

**Comment by cimendes** [comment]
New outputs present as expected:
image

**Comment by cimendes** [comment]
Testing on two identical kraken2 report files here: https://app.terra.bio/#workspaces/theiagen-validations/Theiagen_Mendes_Sandbox/job_history/d590d67a-f893-469e-a281-f1126dc13407

**Comment by cimendes** [comment]
@sage-wright the documentation update is missing for the input and output variables. Do you want to take care of that or should I?

**Comment by cimendes** [comment]
image
image

🌟 Validation worked as expected! 🌟 
Approving once documentation is updated!

**Comment by sage-wright** [comment]
@cimendes, if you have the time to add it to the docs, that'd be great. If not, I think I can get around to it today.

**Comment by cimendes** [comment]
> @cimendes, docs have been updated!

Thank you!!! Approving and merging!

**Pull request merged**
